#!/usr/bin/env python3
"""Write one brief per gematria system into gematria/briefs/."""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "briefs")

SYSTEMS = [
 ("mesopotamian_and_egyptian_precursors", "Mesopotamian and Egyptian precursors of gematria", "Sargon II's Khorsabad inscription (c. 720 BCE): the wall of Dur-Sharrukin built to the length of the value of his name (16,283 cubits) and the reading of it by Lieberman and others; the Babylonian scribal number-name games (the 'Nabu' and the cryptographic writings in Neo-Assyrian scholarship), the god-numbers (Anu 60, Enlil 50, Ea 40, Sin 30, Shamash 20, Ishtar 15) as a proto-gematria; the Egyptian number symbolism and whether hieroglyphic writing ever had letter-values (it did not: say so); Lieberman's 1987 article 'A Mesopotamian Background for the So-Called Aggadic Measures of Biblical Hermeneutics' and its reception"),
 ("greek_isopsephy", "Greek isopsephy", "the alphabetic numerals as the base; the Hellenistic and Roman evidence: the Pompeii graffiti ('I love her whose number is 545', CIL IV 4839), Leonides of Alexandria's isopsephic epigrams for Nero, the Smyrna inscriptions, Lucian's Alexander the false prophet and his 'Glycon' (3663), Artemidorus's dream-book; Revelation 13:18 and the 666 (and 616) as Nero Caesar in Hebrew letters (Irenaeus V.30, the Oxyrhynchus 616), the Sibylline Oracles' 888 for Jesus (I.324-330), Irenaeus I.14-16 on Marcus the Magician (Jesus = 888, the dove = 801 = alpha + omega, the ogdoad of letters, the Aletheia body), the Pistis Sophia's numbers, the magical papyri (the 9999 and the seven vowels), Dornseiff 1922 and Barry 1999; the Byzantine and modern Greek survivals"),
 ("hebrew_standard_gematria", "Hebrew gematria: the standard method (mispar hechrechi)", "the table aleph 1 to tav 400 and the five finals (with the extended values to 900 in mispar gadol), the Talmudic and midrashic uses (Eliezer 318 in Nedarim 32a and Rashi on Gen 14:14; the 'satan' 364 of Yoma 20a; Rabbi Eliezer's 32 rules of Aggadic interpretation, gematria as the 29th), the Sefer Yetzirah's letters, the classic equivalences (ahavah 13 = echad 13, YHVH 26; nachash 358 = mashiach 358; yayin 70 = sod 70, 'when the wine goes in the secret comes out'), the Zohar's uses, the Baal HaTurim's commentary on the Torah (1300s) as the systematic monument, Abulafia's tzeruf, the Hasidic and Lubavitch uses, the modern Torah-codes controversy (Witztum-Rips 1994 and the refutation by McKay et al. 1999) as gematria's cousin; Scholem and Idel on its history; the word's own etymology (Greek geometria or grammateia)"),
 ("hebrew_alternative_methods", "The alternative Hebrew methods: mispar gadol, katan, siduri, kidmi, meruba, milui, and the rest", "the named systems with their tables: mispar gadol (finals 500-900), mispar katan (reduced to single digits), mispar siduri (ordinal 1-22), mispar kidmi (triangular sums), mispar perati and meruba (squares), mispar bone'eh (building), mispar ne'elam (the hidden value of the letter's name minus the letter), mispar milui (the full spelling of each letter, and the four spellings of the Tetragrammaton giving 72, 63, 45, 52 that name the four worlds), mispar shemi, mispar musafi, mispar katan mispari, the 'at-bash' and 'al-bam' as ciphers (separate dossier), the sources for each (the Baal HaTurim, the Ramak's Pardes Rimmonim gate 30, the Ari, the Gra), which are ancient and which are late inventions; the Kabbalah of the four names of God as the great worked example"),
 ("temurah_ciphers_atbash_albam", "Temurah: Atbash, Albam, Avgad and the letter-substitution ciphers", "the substitution systems: Atbash (aleph-tav, bet-shin; Jeremiah 25:26 and 51:41 'Sheshach' for Babel, 51:1 'Leb Kamai' for Kasdim, and the Dead Sea Scrolls' use), Albam, Achbi, Avgad (the shift by one), the Ayak Bakar of the Kabbalists, the 'kabbalah of the nine chambers' (aiq bekar) that the Golden Dawn used for sigils, temurah in the Sefer Yetzirah and in Abulafia, notarikon (acrostic reading: the first-letter and last-letter methods, the 'Adam' = Adam David Messiah) as the sister method; the ciphers' reception in Renaissance cryptography (Trithemius, Agrippa book III, Kircher), Bacon's and Vigenère's debt; the modern uses in the Golden Dawn and in Crowley"),
 ("arabic_abjad_and_ilm_al_huruf", "The Arabic abjad and ilm al-huruf", "the abjad table (the eastern 'abjad hawwaz hutti kalaman' and the western Maghrebi variant with different values for some letters), its Nabataean-Aramaic inheritance and the 28 letters, the muqatta'at (the mysterious letters opening 29 suras) and their gematric readings, the 786 of the bismillah, ilm al-huruf (the science of letters) from Jabir ibn Hayyan and the Ikhwan al-Safa to Ibn Arabi's Futuhat, al-Buni's Shams al-Ma'arif and the magic squares (awfaq, the budduh square), the Hurufis (Fazlallah Astarabadi, d. 1394) and their persecution, jafr (the prophetic letter-science attributed to Ali and Jafar al-Sadiq), the chronogram (tarikh) art in Arabic, Persian, Ottoman Turkish and Urdu (Nabi's and the great Ottoman chronogram poets, the tomb dates, the mosque inscriptions), the Bektashi and Sufi letter-symbolism, the modern Quranic '19' claims of Rashad Khalifa (1974) and their refutation; Encyclopaedia of Islam entries 'Abdjad', 'Huruf', 'Djafr', 'Ta'rikh'"),
 ("latin_chronograms_and_agrippa", "Latin letter-number systems: chronograms and Agrippa's gematria", "the chronogram (chronogrammata, eteostichon): Roman-numeral letters capitalized in an inscription or verse to sum to a year, from the medieval examples through the Jesuit and Baroque golden age (the Hilton collection, the Delft and Dutch chronograms, the Gustavus Adolphus chronograms), the rules and the pure chronogram; Agrippa's De occulta philosophia II.20 (1533) with its Latin, Greek and Hebrew tables (A=1 ... the 1-9, 10-90, 100-900 arrangement with I, V, hi, hu for the extra letters), quoted in the 1651 English; Trithemius; the Renaissance magi's uses (Reuchlin's De arte cabalistica, Pico's conclusions, Kircher's Oedipus Aegyptiacus and Arithmologia), Postel, the Rosicrucian and Masonic uses; the survival of the Latin system in Agrippa-based English occultism"),
 ("indian_katapayadi_and_bhutasamkhya", "Indian letter-number systems: katapayadi, aryabhata's code and the bhutasamkhya", "the katapayadi system (consonants to digits 0-9, read right to left) in the Kerala school and in Carnatic music (the 72 melakarta ragas named so their first two syllables encode their number), the Sadratnamala's pi to 17 places, Aryabhata's alphabetic numeration in the Aryabhatiya (499) with its unique syllable-to-number scheme, the bhutasamkhya word-numerals (moon = 1, eyes = 2, Vedas = 4, senses = 5, seasons = 6, sages = 7, elephants = 8, planets = 9, sky = 0) used in the astronomical texts, the varnasankhya; the Jain and tantric letter-number speculations; whether any of this is 'gematria' in the interpretive sense (mostly not: encoding, not exegesis; say so); Sarma, Plofker, Datta and Singh"),
 ("english_and_pythagorean_numerology", "English and 'Pythagorean' numerology: Balliett, Cheiro and the name-numbers", "the modern popular systems: the 'Pythagorean' table (A=1 to I=9, repeating) invented by L. Dow Balliett (The Philosophy of Numbers, 1908) and spread by Julia Seton, Florence Campbell and Juno Jordan; the 'Chaldean' system of Cheiro (Count Louis Hamon, 1926) with its 1-8 values and its claim to Babylonian origin; the life-path, destiny and expression numbers; the master numbers 11, 22, 33; the absence of any of this in Pythagoras or the Pythagoreans (what the ancient sources actually say about number and the tetractys, Iamblichus, Nicomachus); the 'simple English gematria' A=1..Z=26 and the internet gematria calculators (the gematrinator, 'Jewish gematria', 'English ordinal', 'reverse'), the conspiracy uses (the 33s and 666s of sports and news), the coincidence arithmetic (how many phrases share a sum in a 26-letter system); Underwood Dudley's Numerology, or What Pythagoras Wrought (1997) as the skeptical survey"),
 ("occult_english_qabalahs", "The occult English Qabalahs: Crowley, the Golden Dawn and the New Aeon systems", "the Golden Dawn's use of Hebrew gematria (Sepher Sephiroth, compiled by Allan Bennett and Crowley, 1909), Crowley's 777 and its columns, Liber AL II:76 ('4 6 3 8 A B K 2 4 A L G M O R 3 Y X 24 89 R P S T O V A L') and the century of attempts to find its English key: Achad's, Crowley's own AL = 31 and 'ALW' (the Liber Trigrammaton cipher), James Lees's English Qaballa (ALW, 1976) and the New Aeon English Qabalah, the Trigrammaton Qabalah (R. Leo Gillis), Cipher X, the NAEQ tables; the values and the classic results (ABRAHADABRA = 418 in Hebrew; the 93 of Thelema and Agape in Greek); the Thelemic scholarship and the community disputes; how these differ from the popular English gematria"),
 ("chronograms_hebrew_persian_ottoman", "Chronograms across the letter-number cultures: Hebrew, Persian, Ottoman, Armenian, Cyrillic", "the dating by letter-sums: Hebrew colophons, tombstones and title pages (the printers' chronograms, the 'lifrat katan' small count omitting the thousands), the Persian ta'rikh from the Ghaznavids to the Qajars and its poetic conventions, the Ottoman tarih art (the tarih düşürmek, the great chronogram poets Nabi, Sururi, Ziver; the tombstones of Istanbul; the fountain inscriptions), the Urdu and Mughal chronograms (the Taj Mahal's date, the Sikh chronograms), the Armenian letter-dates in manuscripts and the Georgian, the Cyrillic titlo dates on icons and bells, the Ethiopic; the shared technique across cultures and its social uses (patronage, mourning, dedication)"),
 ("gematria_in_kabbalah_abulafia_and_the_names", "Gematria as mystical practice: Abulafia, the Names and the letter-permutation", "Abraham Abulafia's science of the combination of letters (hokhmat ha-tzeruf) in Or ha-Sekhel, Sefer ha-Ot, Hayyei ha-Olam ha-Ba: the circles of permuted letters, the breathing and head movements, the 72-letter Name (Shemot 14:19-21) and the 42-letter and 22-letter Names, the gematria of the divine names and of Metatron (314 = Shaddai), the Sefer Raziel's names, Eleazar of Worms and the Hasidei Ashkenaz (Sefer ha-Shem, the 73 gates), the Zohar's uses, Cordovero's Pardes gate 30 on the methods, the Lurianic gematria of the four spellings (72, 63, 45, 52), the Baal Shem Tov's use; Scholem's Major Trends lecture IV, Idel's The Mystical Experience in Abraham Abulafia and Language, Torah and Hermeneutics, Wolfson; the practice's transmission to the Christian Kabbalists (Pico, Reuchlin) and to the Golden Dawn (the 72 Shem angels of the Goetia pairing in this repo)"),
]

SIGNS = {}
for i, (slug, name, pointers) in enumerate(SYSTEMS, start=1):
    SIGNS[f"{i:02d}_{slug}"] = (name, f"gematria system {i} of {len(SYSTEMS)} in this set", pointers)

ORDER = list(SIGNS.keys())

if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    for slug, (name, status, pointers) in SIGNS.items():
        text = f"""# {name}: research brief

Gematria research, Anthony 2026-09-15, separate from the atlas. Appended to
PROMPT_TEMPLATE_GEMATRIA.md by tools/codex_dossier_set.py.

---

SYSTEM. {name}: {status}. Give at the top the script, the period, the region and the table of
values.

THREADS TO PULL, each to be verified against the sources and dated: {pointers}.

STANCE. Legend as fully as fact. Every claim labeled: documented text, scholarly reconstruction,
tradition, disputed, legend, modern invention. Show the arithmetic of every worked example.
Where a system claims antiquity it does not have (the 'Pythagorean' and 'Chaldean' name-numbers,
the modern English gematrias), say when it was actually invented and by whom. Absence of
evidence is a finding.
"""
        open(os.path.join(OUT, f"{slug}.brief.md"), "w").write(text)
    print("wrote", len(SIGNS), "briefs")
