#!/usr/bin/env python3
"""Write one brief per tribe of Israel into working/tribes/briefs/: the twelve sons of Jacob in
birth order, Joseph's dossier covering Ephraim and Manasseh."""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "briefs")

SIGNS = {
 "reuben": ("Reuben", "first son of Jacob and Leah", "'unstable as water, thou shalt not excel' (Gen 49:3-4), the mandrakes (Gen 30:14), Bilhah (Gen 35:22), the pit and Joseph (Gen 37:21-22, 29); Deut 33:6 'let Reuben live and not die'; the Transjordan allotment with Gad (Num 32, Josh 13:15-23), Heshbon, Dibon, Aroer, the Mesha stele's Gadites; the Song of Deborah's reproach (Judg 5:15-16); the altar of witness (Josh 22); the stone: sardius/ruby (odem); the banner: red with mandrakes (Bamidbar Rabbah 2:7); Blavatsky: Reuben as Aquarius, the water-bearer, 'unstable as water' (check Isis Unveiled II and SD I for the exact page); the lost-tribe fate east of the Jordan under Tiglath-Pileser III (1 Chr 5:26)"),
 "simeon": ("Simeon", "second son of Jacob and Leah", "'hearing' (Gen 29:33); Shechem and Dinah with Levi (Gen 34); the hostage in Egypt (Gen 42:24); Jacob's curse 'instruments of cruelty… I will divide them in Jacob' (Gen 49:5-7); absent from Moses' blessing (Deut 33) and the reasons given; the allotment inside Judah (Josh 19:1-9), Beersheba, Ziklag, Hormah; Zimri and the Baal-Peor affair (Num 25); the diminished census; the Simeonites' migration to Gedor and Mount Seir (1 Chr 4:24-43); the stone: topaz/pitdah; the banner: green with Shechem; Blavatsky and the Simeon-Levi pair as Gemini (or Pisces in other schemes): quote her; the Testament of Simeon on envy"),
 "levi": ("Levi", "third son of Jacob and Leah", "'joined' (Gen 29:34); Shechem (Gen 34); the curse of Gen 49:5-7 turned into priesthood (Deut 33:8-11, Thummim and Urim); the golden calf and the Levites' sword (Exod 32:26-29); Moses, Aaron, Miriam, Korah, Phinehas; no territorial allotment, the 48 Levitical cities and the six cities of refuge (Num 35, Josh 21); the Kohathites, Gershonites, Merarites and the tabernacle; the priesthood and the Levites in the Temple, the Zadokites, the Hasmoneans; the stone: emerald/bareqet; the banner: a third white, a third black, a third red, with the Urim and Thummim; Blavatsky's assignment (Gemini with Simeon, or Libra?) verbatim; the Levites today (Cohen and Levi surnames, the Cohen Modal Haplotype genetics), the Samaritan priesthood"),
 "judah": ("Judah", "fourth son of Jacob and Leah", "'praise' (Gen 29:35); Tamar (Gen 38); the surety for Benjamin (Gen 43-44); 'Judah is a lion's whelp… the sceptre shall not depart from Judah… until Shiloh come' (Gen 49:8-12) with the Shiloh crux; Deut 33:7; the largest allotment (Josh 15), Hebron, Bethlehem, Jerusalem's border; Caleb, Othniel, Achan, Boaz, Jesse, David and the whole Davidic line, the kingdom of Judah 931-586, Hezekiah, Josiah, the exile and return, 'Jew' from Judah; the lion of Judah (Ethiopia's emperors, Revelation 5:5, the Rastafari); the stone: carbuncle/nofekh (or emerald); the banner: sky-blue with a lion; Blavatsky: Judah as Leo, verbatim; the Messiah ben David; Judah in Islamic tradition"),
 "dan": ("Dan", "first son of Jacob and Bilhah, Rachel's maid", "'judge' (Gen 30:6); 'Dan shall be a serpent by the way, an adder in the path… I have waited for thy salvation, O LORD' (Gen 49:16-18); 'a lion's whelp: he shall leap from Bashan' (Deut 33:22); the coastal allotment lost to the Amorites and the migration north to Laish/Dan (Judg 18) with Micah's idol and the Levite; Samson (Judg 13-16); Oholiab the craftsman (Exod 31:6); Jeroboam's golden calf at Dan (1 Kgs 12:29); 'from Dan to Beersheba'; the Tel Dan stele and the 'House of David'; Dan omitted from Revelation 7 and the Antichrist-from-Dan tradition (Irenaeus, Hippolytus); the stone: leshem (jacinth/ligure); the banner: sapphire-blue with a serpent (or scales); Blavatsky: Dan as Scorpio, the serpent, and the eagle, verbatim; the Beta Israel of Ethiopia as Dan (Eldad ha-Dani, the 1973 Ovadia Yosef ruling); the Danites and the Danaans/Tuatha Dé Danann claim (British Israelism)"),
 "naphtali": ("Naphtali", "second son of Jacob and Bilhah", "'my wrestlings' (Gen 30:8); 'a hind let loose: he giveth goodly words' (Gen 49:21) with the LXX 'spreading terebinth' variant; 'satisfied with favour… possess thou the west and the south' (Deut 33:23); the Galilee allotment (Josh 19:32-39), Hazor, Kedesh, Chinnereth, the Sea of Galilee; Barak of Kedesh and Deborah's war (Judg 4-5); Hiram's mother of Naphtali (1 Kgs 7:14); the first deportation under Tiglath-Pileser (2 Kgs 15:29); Isaiah 9:1 and Matthew 4:13-16 'land of Zebulun and land of Naphtali… Galilee of the nations' and Jesus at Capernaum; Tobit of Naphtali; the stone: amethyst/ahlamah; the banner: wine-red with a hind; Blavatsky: Naphtali as Capricorn? (the hind/goat) verbatim; the Testament of Naphtali"),
 "gad": ("Gad", "first son of Jacob and Zilpah, Leah's maid", "'a troop cometh' / 'good fortune' (Gen 30:11) and the deity Gad (Isa 65:11); 'a troop shall overcome him, but he shall overcome at the last' (Gen 49:19); 'he dwelleth as a lion… he executed the justice of the LORD' (Deut 33:20-21); the Transjordan allotment with Reuben (Num 32), Gilead, Jazer, Ramoth-gilead; the Mesha stele: 'the men of Gad had dwelt in Ataroth from of old'; Jephthah the Gileadite?; Elijah the Tishbite of Gilead; the Gadites who came to David 'faces like lions' (1 Chr 12:8); the stone: agate/shevo; the banner: grey/black-white with a camp; Blavatsky: Gad as Aries? verbatim; deported 732 BCE"),
 "asher": ("Asher", "second son of Jacob and Zilpah", "'happy' (Gen 30:13); 'out of Asher his bread shall be fat, and he shall yield royal dainties' (Gen 49:20); 'let Asher be blessed with children… let him dip his foot in oil… thy shoes shall be iron and brass' (Deut 33:24-25); the coastal allotment north of Carmel (Josh 19:24-31), Acco, Tyre and Sidon on its border, the olive oil of the Galilee; Deborah's reproach 'Asher continued on the sea shore' (Judg 5:17); Anna the prophetess of Asher (Luke 2:36); the stone: beryl/tarshish (or chrysolite); the banner: pearl-coloured with an olive tree; Blavatsky: Asher as Libra? verbatim; the daughters of Asher in Midrash (Serah bat Asher who never died)"),
 "issachar": ("Issachar", "fifth son of Jacob and Leah", "'hire/reward' (Gen 30:18) and the mandrakes bargain; 'a strong ass couching down between two burdens… became a servant unto tribute' (Gen 49:14-15); 'rejoice, Zebulun, in thy going out, and Issachar, in thy tents' (Deut 33:18-19); the Jezreel valley allotment (Josh 19:17-23), Jezreel, Shunem, Mount Tabor, Endor; Tola the judge (Judg 10:1); Baasha king of Israel of Issachar; 'the children of Issachar, which were men that had understanding of the times' (1 Chr 12:32) and the tradition that Issachar produced the astronomers and calendar-makers of the Sanhedrin; the stone: sapphire/sappir (lapis lazuli); the banner: black with sun and moon; Blavatsky: Issachar as Taurus? (the ass/ox) verbatim; the Zebulun-Issachar partnership of merchant and scholar (Bereshit Rabbah 99:9)"),
 "zebulun": ("Zebulun", "sixth son of Jacob and Leah", "'dwelling/honour' (Gen 30:20); 'Zebulun shall dwell at the haven of the sea; and he shall be for an haven of ships; and his border shall be unto Zidon' (Gen 49:13); 'rejoice, Zebulun, in thy going out' (Deut 33:18); the lower Galilee allotment (Josh 19:10-16), Nazareth's region, Bethlehem of Galilee, Gath-hepher (Jonah of Zebulun); Elon the judge (Judg 12:11-12); Deborah's praise 'jeoparded their lives unto the death' (Judg 5:18); Isa 9:1 and Matthew 4; the stone: diamond/yahalom; the banner: white with a ship; Blavatsky: Zebulun as Pisces? or Cancer? verbatim; the merchant tribe and the Issachar partnership"),
 "joseph": ("Joseph", "eleventh son of Jacob, first of Rachel; with Ephraim and Manasseh", "'may he add' (Gen 30:24); the whole Joseph novella (Gen 37-50): the coat, the dreams, the pit, Potiphar, the prison, Pharaoh's dreams, Zaphenath-paneah, Asenath, the famine, the reconciliation, the bones carried to Shechem; 'Joseph is a fruitful bough… the archers have sorely grieved him… his bow abode in strength' (Gen 49:22-26); 'his glory is like the firstling of his bullock, and his horns are like the horns of unicorns' (Deut 33:13-17); Ephraim and Manasseh adopted by Jacob and the crossed hands (Gen 48); the two half-tribes, the hill country of Ephraim and both banks for Manasseh (Josh 16-17), Shechem, Shiloh, Bethel, Samaria; Joshua of Ephraim, Gideon and Jephthah? of Manasseh, Jeroboam of Ephraim and the northern kingdom as 'Ephraim' in Hosea; the Samaritans as Joseph's remnant to this day; the stones: onyx/shoham (Joseph) and the Ephraim/Manasseh assignments; the banner: black with Egypt (Joseph), Ephraim's bullock and Manasseh's wild ox; Blavatsky: Joseph as Sagittarius (the archer), verbatim, and where she puts Ephraim and Manasseh; Messiah ben Joseph; British Israelism's Ephraim = Britain, Manasseh = USA; the Bnei Menashe of Manipur and Mizoram; Joseph in the Qur'an (Sura 12)"),
 "benjamin": ("Benjamin", "twelfth son of Jacob, second of Rachel", "'son of my right hand' / Ben-oni 'son of my sorrow' (Gen 35:18), Rachel's death at Ephrath; the silver cup (Gen 44); 'Benjamin shall ravin as a wolf: in the morning he shall devour the prey, and at night he shall divide the spoil' (Gen 49:27); 'the beloved of the LORD shall dwell in safety by him… he shall dwell between his shoulders' (Deut 33:12) and the Temple on Benjamin's land; the allotment between Judah and Ephraim (Josh 18:11-28), Jerusalem, Jericho, Gibeah, Gibeon, Bethel, Mizpah, Ramah; the outrage at Gibeah and the near-extinction of the tribe (Judg 19-21); Ehud the left-handed judge (Judg 3), the 700 left-handed slingers (Judg 20:16); Saul of Gibeah, the first king; Mordecai and Esther 'a Benjamite'; Paul of Tarsus 'of the tribe of Benjamin' (Rom 11:1, Phil 3:5); the stone: jasper/yashfeh; the banner: many-coloured with a wolf; Blavatsky: Benjamin as ? verbatim; Benjamin with Judah as the surviving southern kingdom"),
}

ORDER = list(SIGNS.keys())

if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    for slug, (name, status, pointers) in SIGNS.items():
        text = f"""# {name}: research brief

Twelve tribes of Israel research, Anthony 2026-09-14, separate from the atlas. Appended to
PROMPT_TEMPLATE_TRIBE.md by atlas_tools/codex_dossier_tribes.py.

---

FIGURE. {name}: {status}. Give at the top the name, its meaning, the mother, the birth order,
the emblem, the breastplate stone, the banner, the month, the camp direction, and the zodiac sign
Blavatsky assigns.

THREADS TO PULL, each to be verified against the sources and dated: {pointers}.

STANCE. Legend as fully as fact. Every claim labeled: documented text, scholarly reconstruction,
rabbinic tradition, esoteric correspondence, modern claim, legend. Where a thread above carries a
question mark, treat it as a lead to check and report what you found; for Blavatsky, quote the
passage with volume and page rather than paraphrasing, and if she gives no explicit sign for this
tribe, say so and give the nearest thing she does say. Absence of evidence is a finding.
"""
        open(os.path.join(OUT, f"{slug}.brief.md"), "w").write(text)
    print("wrote", len(SIGNS), "briefs")
