#!/usr/bin/env python3
"""Write one brief per hero into heroes/briefs/. Dossiers land as <tradition>/<slug>.md
(Anthony, 2026-09-17: "let's have a collection of heroes from different traditions", separate
from the pantheon and from the atlas). Same machinery as pantheon/make_briefs.py.
"""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "briefs")

TRADITIONS = {
 "greek": ("Greek", "Homer (Iliad, Odyssey), the Epic Cycle fragments (West's Loeb), Hesiod's Catalogue of Women, Pindar, the tragedians, Apollonius's Argonautica, Apollodorus's Bibliotheca, Pausanias, Hyginus, Ovid, the scholia, the LIMC for the vases; Gantz's Early Greek Myth, Nagy's The Best of the Achaeans and Greek Hero Cults, Farnell's Greek Hero Cults, Burkert, Ekroth on hero cult, Fowler's Early Greek Mythography, the Theoi.com source index, Perseus and the TLG"),
 "roman": ("Roman", "Virgil's Aeneid with Servius's commentary, Livy I-II, Dionysius of Halicarnassus, Ovid's Fasti and Metamorphoses, Plutarch's Romulus and Publicola, Dio, the Fasti Capitolini, the Lapis Niger, the Lupercal and the Lavinium heroon archaeology; Wiseman's Remus, Cornell's Beginnings of Rome, Dumézil, Grandazzi, Horsfall's commentaries, the Brill's New Pauly"),
 "norse": ("Norse and Germanic", "the Poetic Edda (the heroic poems), the Völsunga saga, the fornaldarsögur (Hervarar saga, Ragnars saga, Gautreks saga), Saxo Grammaticus, Beowulf (Klaeber's edition, Tolkien's essay) and Grettis saga, the Nibelungenlied and the Thidrekssaga, the Egils saga, the Icelandic family sagas; Simek, Turville-Petre, Andersson's The Legend of Brynhild, Tolkien, Orchard's Critical Companion to Beowulf, Rowe on the fornaldarsögur, the Skaldic Project"),
 "persian": ("Persian", "Ferdowsi's Shahnameh (Khaleghi-Motlagh's edition, Davis's translation, Warner and Warner), the Avesta's yashts where the heroes appear (Yasht 19 for Fereydun and Garshasp), the Bundahishn and Denkard, the Garshaspnameh of Asadi Tusi, the Borzunameh, Tabari and Bal'ami, the Sasanian Khwaday-namag tradition; the Encyclopaedia Iranica, Yarshater's Cambridge History of Iran III, Omidsalar, Davidson's Poet and Hero, the Shahnameh illustrations (the Great Mongol, the Shah Tahmasp)"),
 "hindu": ("Hindu (the Mahabharata)", "the Mahabharata critical edition (Poona; van Buitenen, Ganguli, the Clay Sanskrit Library), the Harivamsa, the regional Mahabharatas and folk cults (the Draupadi cult of Tamil Nadu, Hiltebeitel; the Karna of the Marathi tradition), the Bhagavad Gita for Arjuna, Bhasa's plays, the Kathakali and Yakshagana repertoires, the 1988 TV serial as reception; Hiltebeitel's The Ritual of Battle, Biardeau, Brockington's The Sanskrit Epics, Sukthankar, Doniger, the Sanskrit at GRETIL"),
 "celtic": ("Celtic (Irish and Welsh)", "the Ulster Cycle (the Táin in Kinsella's and O'Rahilly's versions, the Death of Aífe's Only Son, Bricriu's Feast, the Exile of the Sons of Uisliu), the Fenian Cycle (the Acallam na Senórach, Macgnímartha Finn, the Pursuit of Diarmuid and Gráinne), the Mabinogion (Culhwch ac Olwen), the Book of Taliesin, the Dindshenchas; Ó hÓgáin's Fionn mac Cumhaill and The Lore of Ireland, Nagy's The Wisdom of the Outlaw, Ford's Ystoria Taliesin, MacKillop, the CELT corpus, the Ossian controversy (Macpherson) as reception"),
 "slavic": ("Slavic (the byliny)", "the byliny collections (Kirsha Danilov's of the 18th century, Rybnikov, Hilferding, Gilferding's Onega singers), the Kiev and Novgorod cycles, the Russian Primary Chronicle for the historical shadows, the lubok prints; Bailey and Ivanova's An Anthology of Russian Folk Epics, Propp's Russian Heroic Epic, Oinas, the Vasnetsov Bogatyrs (1898) and the Soviet reception, Rimsky-Korsakov's Sadko"),
 "finnic": ("Finnic (the Kalevala)", "the Kalevala (Lönnrot 1835 and 1849; Bosley's translation) and the SKVR runes behind it (Suomen Kansan Vanhat Runot), the Kanteletar, Ganander's Mythologia Fennica, Castrén; Haavio's Väinämöinen: Eternal Sage, Siikala, Pentikäinen's Kalevala Mythology, Honko, Kaukonen on Lönnrot's method, Sibelius and Gallen-Kallela as reception, the Kalevala's role in Finnish nationhood"),
 "japanese": ("Japanese", "the Kojiki and Nihon Shoki (Yamato Takeru), the Heike monogatari and Gikeiki (Yoshitsune and Benkei), the otogizōshi and the Edo picture books (Momotarō, Kintarō, Urashima), the Nihon ryōiki and Konjaku, the Kabuki and Noh repertoires, the Meiji school readers that fixed Momotarō; Antoni, Reider, Foster, Kōji Kawamoto, McCullough's Heike, the Yoshitsune-as-Genghis-Khan legend as documented modern invention, the wartime Momotarō propaganda films"),
 "mesopotamian": ("Mesopotamian", "the Etana epic (Kinnier Wilson, Novotny), the Sargon Birth Legend (Lewis's The Sargon Legend), the Sumerian King List, the Old Akkadian inscriptions and the Sargon legends of the first millennium (the King of Battle), the ETCSL and ORACC; Westenholz's Legends of the Kings of Akkade, Foster's Before the Muses, George on Gilgamesh for the comparanda"),
 "biblical": ("Biblical (the mythic figures of the Hebrew Bible, between the atlas and the angels)", "the Hebrew Bible (the Masoretic text, the Septuagint and the Vulgate where they differ, the Dead Sea Scrolls), the Pseudepigrapha (1 Enoch, Jubilees, the Life of Adam and Eve, the Testaments), Josephus's Antiquities, the Talmud and the midrash (Genesis Rabbah, Pirke de-Rabbi Eliezer), Ginzberg's Legends of the Jews for the whole rabbinic layer, the Qur'an and the qisas al-anbiya (al-Tha'labi, al-Kisa'i) for the Islamic figure, the Church Fathers and the Glossa, the medieval mystery plays and the iconography (the Princeton Index), the archaeology where it bears (the minimalist debate: Finkelstein, Dever), the Anchor Bible Dictionary, the DDD, Alter's translation and commentary, Kugel's Traditions of the Bible, the Encyclopaedia Judaica"),
 "yoruba": ("Yoruba", "Samuel Johnson's History of the Yorubas (1921), the Ife and Oyo oral histories (the Oranmiyan staff at Ife, the Moremi festival at Ife, the Edi festival), Akinjogbin, Law's The Oyo Empire, Obayemi, Bascom, Peel; the Benin chronicles for Oranmiyan (Egharevba), the Moremi statue at Ile-Ife (2016) and the Queen Moremi Ajasoro musical as reception"),
}

ROSTER = [
 # ---------------- GREEK ----------------
 ("greek","achilles","Achilles","the best of the Achaeans: Thetis and Peleus, the heel (a late tale: Statius), Chiron, Scyros and the girls, the wrath and Briseis, Patroclus's death and the shield, Hector dragged, the arrow of Paris, the funeral games, Leuke and the cult at Sigeion and Olbia, Alexander at his tomb, Nagy's Best of the Achaeans, Homer's Achilles against the Cypria's"),
 ("greek","hector","Hector","the Trojan champion: Andromache and Astyanax at the gate, the duel with Ajax, Patroclus killed, the flight round the walls and the death, the body ransomed by Priam, the cult at Thebes (his bones brought from Troy, Pausanias IX.18), the medieval Hector of the Nine Worthies"),
 ("greek","agamemnon","Agamemnon","the king of Mycenae: Iphigenia at Aulis, the quarrel with Achilles, the return and the bath, the murder by Clytemnestra and Aegisthus (Odyssey XI, Aeschylus, Pindar's Amyclae version), the cult at Mycenae's Agamemnoneion, the Mask of Agamemnon (Schliemann 1876) as reception, the Hittite Akagamunas question"),
 ("greek","menelaus","Menelaus","Helen's husband: the wooing and the oath, the war for her, the duel with Paris, the wooden horse, the wanderings and Proteus in Egypt (Odyssey IV), the Menelaion at Sparta and the cult with Helen, the Elysium promised him, Euripides's Helen and the Egyptian phantom"),
 ("greek","helen","Helen of Troy","the daughter of Zeus and Leda (or Nemesis), the egg, Theseus's abduction, the suitors' oath, Paris and the flight, the teichoskopia, the phantom Helen of Stesichorus and Euripides, the return to Sparta, the cult at Therapne and the Menelaion, Helen the goddess, Gorgias's Encomium, Faustus's Helen and the modern Helens"),
 ("greek","paris","Paris (Alexandros)","the judgment of the goddesses, the exposure on Ida and the herdsman, Oenone, the abduction of Helen, the duel with Menelaus and Aphrodite's rescue, the arrow that killed Achilles, the death by Philoctetes's arrow, the Cypria and the Iliad, the judgment in art from the Chigi vase to Rubens"),
 ("greek","priam","Priam","the last king of Troy: the fifty sons, the ransom of Hector's body in Achilles's hut (Iliad XXIV), the death at the altar by Neoptolemus (the Iliupersis, Aeneid II), the Priam of the Hittite Piyamaradu question, Priam's treasure (Schliemann) as reception"),
 ("greek","ajax","Ajax (the Greater, son of Telamon)","the bulwark of the Achaeans with the tower shield, the duel with Hector, the defence of the ships, the rescue of Achilles's body, the judgment of the arms and the madness among the sheep, the suicide on the sword (Sophocles), the cult at Salamis and the Aianteia, the flower with AI"),
 ("greek","diomedes","Diomedes","the son of Tydeus who wounded Aphrodite and Ares (Iliad V), the night raid with Odysseus (Iliad X), the Palladium stolen, the return to Argos and Aphrodite's revenge, the foundations in Italy (Arpi, the Diomedean islands, the birds), the cult in Apulia"),
 ("greek","patroclus","Patroclus","Achilles's companion: the exile for a boyhood killing, the fostering at Phthia, the armour borrowed and the death by Apollo, Euphorbus and Hector, the funeral games and the ghost's request (Iliad XXIII), the shared urn, the nature of the bond in the ancient debate (Aeschylus's Myrmidons, Plato's Symposium) and the modern"),
 ("greek","nestor","Nestor","the old king of Pylos who outlived two generations, the Gerenian horseman, the counsellor of the Iliad, Telemachus's host (Odyssey III), the Cup of Nestor (Iliad XI and the Pithekoussai inscription, c. 730 BCE, the earliest Homeric allusion), the Palace of Nestor at Pylos and its tablets"),
 ("greek","penelope","Penelope","the weaver of Laertes's shroud, the twenty years, the suitors and the bow, the bed built round the olive, the Odyssey's recognition, the alternative Penelopes (the mother of Pan by Hermes or by all the suitors, Duris and Apollodorus), the Penelope of Ovid's Heroides and of the modern retellings (Atwood)"),
 ("greek","telemachus","Telemachus","the son who sailed to Pylos and Sparta (the Telemachy), Athena as Mentor, the return and the bow, the killing of the suitors beside his father, the Telegony's ending (Telemachus married to Circe), Fénelon's Télémaque and the mentor word"),
 ("greek","odysseus_hero","Odysseus (the hero and his cult)","not the journey (the atlas has it) but the figure: the son of Laertes (or Sisyphus), the boar's scar, the wooden horse, the Palladium, the judgment of the arms, the nostos and the suitors, the death by Telegonus's spear (the Telegony), the cult in Ithaca (the Polis cave tripods) and in Aetolia and Epirus, the Odysseus of tragedy as villain, the Latin Ulixes and Dante's Ulisse, the modern Ulysses"),
 ("greek","perseus","Perseus","Danaë and the golden rain, the chest, Polydectes, the Graeae and the nymphs' gifts, Medusa beheaded, Andromeda and the sea monster, the petrification of Polydectes, the discus that killed Acrisius, the founding of Mycenae, the cult at Mycenae and Seriphos, the constellations, the Persians descended from him (Herodotus VII.61), Cellini's bronze"),
 ("greek","theseus","Theseus","the sword and sandals under the rock, the six labours of the road, the Marathonian bull, the Minotaur and Ariadne's thread, the black sail and Aegeus's fall, the synoecism of Athens, the Amazon Antiope, Phaedra and Hippolytus, the abduction of Helen and the chair in Hades, the death on Scyros, Cimon's recovery of the bones (476 BCE) and the Theseion, Plutarch's Life, the democratic Theseus"),
 ("greek","jason","Jason","the one-sandalled man, Pelias's task, the Argo and the crew, Lemnos, the Clashing Rocks, Colchis and Medea's help, the fleece, the return by strange rivers, Pelias's death in the cauldron, Corinth and the murder of the children, the beam of the Argo that killed him (Euripides's prologue), Apollonius against Pindar's Pythian 4"),
 ("greek","medea","Medea","the granddaughter of Helios, the help to Jason, the murder of Apsyrtus, the rejuvenation of Aeson and the death of Pelias, Corinth and the killing of the children (Euripides 431, and the older Corinthian versions where the Corinthians killed them), the flight in the dragon chariot, Athens and Aegeus, the Medea of Seneca and of Pasolini, the witch and the wronged woman"),
 ("greek","orpheus","Orpheus","the Thracian singer son of Calliope, the Argonaut, the descent for Eurydice and the look back (Virgil's Georgics IV and Ovid; the older happy versions), the death by the maenads and the singing head at Lesbos, the Orphic mysteries and the gold tablets, the Orphic poems, Orpheus in the catacombs as Christ, Monteverdi and Gluck, Cocteau"),
 ("greek","cadmus","Cadmus","the Phoenician who followed the cow and founded Thebes, the dragon's teeth and the Spartoi, Harmonia's wedding attended by the gods, the letters brought to Greece (Herodotus V.58), the grandfather of Dionysus, the transformation into a snake in Illyria, the Cadmeia and the Theban cult"),
 ("greek","bellerophon","Bellerophon","the tamer of Pegasus with Athena's bridle, the false accusation of Stheneboea and the letter of death, the Chimera, the Solymi and the Amazons, the Lycian kingdom, the attempted flight to Olympus and the fall (Pindar's Isthmian 7), the Corinthian cult and the Peirene spring"),
 ("greek","oedipus","Oedipus","the oracle, the exposure, the crossroads and Laius, the Sphinx's riddle, Jocasta, the plague and the discovery (Sophocles), the blinding, Colonus and the mysterious death that protects Athens, the older Oedipus of Homer who kept ruling, the curse on the sons, the hero cult at Colonus and Eteonos, Freud's complex as reception"),
 ("greek","antigone","Antigone","the daughter who buried Polynices against Creon's edict, the cave and the hanging, Haemon's death (Sophocles 441), the Antigone of Euripides's lost play (married to Haemon), the Seven against Thebes and the Phoenissae, Anouilh's and Brecht's Antigones, Hegel's reading, the Antigone of the Argentine and Latin American stage"),
 ("greek","atalanta","Atalanta","the exposed girl suckled by a bear, the huntress of the Calydonian boar and the first wound, Meleager's gift, the footrace and the golden apples of Hippomenes (or Melanion), the lions of Cybele, the Argonaut question, the Arcadian and Boeotian Atalantas"),
 ("greek","meleager","Meleager","the brand in the fire (the Fates' condition) and Althaea's revenge, the Calydonian boar hunt and the hide given to Atalanta, the killing of his uncles, the older Meleager of the Iliad (Phoenix's tale, IX.529-599) who dies otherwise, the Meleagrids weeping as guinea-fowl"),
 ("greek","philoctetes","Philoctetes","the heir of Heracles's bow who lit the pyre, the snakebite and the abandonment on Lemnos, the ten years, the prophecy and the embassy of Odysseus and Neoptolemus (Sophocles 409), the killing of Paris, the cult in Italy (Sybaris, Macalla), the wound as the modern metaphor (Wilson's The Wound and the Bow)"),
 ("greek","neoptolemus","Neoptolemus (Pyrrhus)","Achilles's son fetched from Scyros, the killing of Priam at the altar and of Astyanax, Polyxena sacrificed at his father's tomb, Andromache his captive, the death at Delphi (killed by the priests or by Orestes) and the hero cult there (Pindar's Nemean 7, Pausanias), the Molossian kings descended from him, Racine's Pyrrhus"),
 ("greek","iphigenia","Iphigenia","the daughter sacrificed at Aulis for the winds (or replaced by a deer: the Cypria, Euripides), Iphigenia among the Taurians and the rescue by Orestes, the priestess of Artemis at Brauron and Halae, the Iphigenia-Hecate identification (Hesiod's Catalogue), Aeschylus's Agamemnon, Gluck and Goethe"),
 ("greek","cassandra","Cassandra","the prophetess believed by no one, Apollo's gift and the spit, the warning about the horse, the rape by the Lesser Ajax at Athena's statue, the captive of Agamemnon and the death at Mycenae (Aeschylus's Agamemnon), Lycophron's Alexandra, the cult at Amyclae and Leuctra, Christa Wolf's Kassandra"),
 ("greek","andromeda","Andromeda","the Ethiopian princess chained for her mother's boast, Perseus and the sea monster, the marriage and the quarrel with Phineus, the constellation, the Jaffa localization (the chains shown by Pausanias), the Euripides play and the Aristophanic parody, the paintings from Titian to Burne-Jones"),
 ("greek","daedalus_and_icarus","Daedalus and Icarus","the craftsman exiled for killing Perdix, the cow for Pasiphae and the labyrinth, the wings and the fall into the Icarian sea, Cocalus in Sicily and the death of Minos in the bath, the Daedalic style and the first statues that moved, Icarus in Bruegel and Auden, the Daedalus of Joyce"),
 ("greek","tantalus","Tantalus","the king who served his son Pelops to the gods, the theft of nectar or the secrets told, the punishment in Hades (the fruit and the water, the stone overhead), the house of Atreus that follows, the Lydian Sipylus and the tomb shown, the word tantalize"),
 ("greek","sisyphus","Sisyphus","the founder of Corinth who chained Death and tricked Persephone, the stone in Hades, the father of Odysseus in the anti-Odyssean tradition, the Isthmian games founded for Melicertes, Camus's Myth of Sisyphus"),
 ("greek","pelops","Pelops","the boy served at the gods' table and restored with an ivory shoulder, Poseidon's lover, the chariot race with Oenomaus and the treachery of Myrtilus, Hippodamia, the Peloponnese named for him, the hero cult at Olympia (the Pelopion, the black ram) as the games' founding, the curse on his house"),
 ("greek","orestes","Orestes","the son who avenged Agamemnon by killing Clytemnestra and Aegisthus, the Furies and the flight, the trial at the Areopagus and Athena's vote (the Eumenides), the Taurian rescue of Iphigenia, Hermione, the death by snakebite in Arcadia, the bones brought to Sparta by Lichas (Herodotus I.67-68), the Oresteia and its reception (Sartre, O'Neill)"),
 ("greek","argonauts","The Argonauts","the crew of the Argo as a collective: the catalogue (Apollonius I, Pindar's Pythian 4, Apollodorus, the Orphic Argonautica), the voyage stage by stage, the Argo itself built with Athena's help and set among the stars, the return routes (the Danube, the Nile, the ocean), the Argonauts' cults along the Black Sea and the Adriatic, Jason and Medea have their own files"),
 # ---------------- ROMAN ----------------
 ("roman","aeneas_hero","Aeneas (the hero and his cult)","not the journey (the atlas has it) but the figure: Homer's Aeneas rescued by Poseidon for the future rule over the Trojans (Iliad XX), the Aeneas of Stesichorus and the Tabula Iliaca, the Etruscan Aeneas statuettes of Veii (5th c. BCE), the Lavinium heroon (the 7th-century tumulus re-cult in the 4th) and the Sol Indiges, Virgil's Aeneas and the pietas, Dido, the Julian descent, the medieval Aeneas of the Roman d'Eneas and Dante"),
 ("roman","turnus","Turnus","the Rutulian king promised Lavinia, Allecto's fury, the war of the second half of the Aeneid, the killing of Pallas and the belt, the duel and the death by Aeneas's sword as the poem's last line, the Turnus of the Italian nationalists and of the Vietnam-era readings, Ardea"),
 ("roman","evander","Evander","the Arcadian who founded Pallantium on the Palatine, the host of Aeneas (Aeneid VIII, the tour of the future Rome), the father of Pallas, the Lupercalia and the letters brought to Italy, Carmenta his mother, the Ara Maxima's founding with Hercules"),
 ("roman","ascanius","Ascanius (Iulus)","the son who followed his father from Troy, the omen of the flame, the founder of Alba Longa, the Julian gens's ancestor by the name Iulus, the Ascanius of the Latin annalists against Virgil's, the Alban kings"),
 ("roman","lavinia","Lavinia","the daughter of Latinus whose hair caught fire, the bride promised and fought for, the founder-name of Lavinium, the mother of Silvius born in the woods after Aeneas's death, the silent Lavinia of Virgil and the speaking one of Ursula Le Guin, the Lavinium excavations"),
 ("roman","camilla","Camilla","the Volscian warrior maiden dedicated to Diana, carried across the river on a spear as a baby, the huntress who runs over the wheat, the cavalry battle and the death by Arruns's spear (Aeneid XI), the Amazon type in Latium, the Camilla of the Italian Renaissance and of Le Guin"),
 ("roman","nisus_and_euryalus","Nisus and Euryalus","the two friends of the night raid through the Rutulian camp, the helmet's gleam and the death together (Aeneid IX), 'fortunati ambo', the Roman ideal of amicitia and the pederastic reading, the games of book V"),
 ("roman","pallas","Pallas (son of Evander)","the young Arcadian entrusted to Aeneas, killed by Turnus and stripped of the belt, the funeral (Aeneid XI) and the belt that decides the ending, the Pallantium and the Palatine's name"),
 ("roman","romulus_and_remus","Romulus and Remus","the twins of Rhea Silvia and Mars, the Tiber, the wolf and Faustulus, the augury and the wall, Remus killed, the Sabine women, the apotheosis as Quirinus (or the murder by the senators), the Lupercal (the cave found in 2007, disputed), the Capitoline Wolf's date (medieval, 2012 radiocarbon), Wiseman's Remus on the invention of the twin, the fascist and the modern Rome"),
 ("roman","horatius_cocles","Horatius Cocles","the one-eyed man who held the Sublician bridge against Porsenna's Etruscans (Livy II.10, Polybius VI.55 with his death), the statue in the Comitium, the Vulcanal, Macaulay's Lay, Dumézil's one-eyed and one-handed pair with Scaevola"),
 ("roman","mucius_scaevola","Gaius Mucius Scaevola","the youth who burned his right hand in the fire before Porsenna and won the peace (Livy II.12-13), the Mucia Prata, the left-handed cognomen, Dumézil's reading, the paintings (Rubens, van Dyck)"),
 ("roman","cloelia","Cloelia","the hostage girl who swam the Tiber with her companions from Porsenna's camp (Livy II.13), the equestrian statue on the Via Sacra (the earliest to a woman), the exemplum in Valerius Maximus and Boccaccio's De mulieribus claris, the Renaissance cassoni"),
 # ---------------- NORSE ----------------
 ("norse","beowulf","Beowulf","the Geat who killed Grendel and Grendel's mother in Heorot and the dragon at home, the poem (Cotton Vitellius A.xv, the dating fight from the 8th to the 11th century), the Swedish-Geatish wars in the background, Bödvar Bjarki as cognate, the barrow and the funeral, Tolkien's 1936 lecture, the Heaney translation, the films"),
 ("norse","starkad","Starkad (Starkaðr)","the giant-born hero with the extra arms Thor tore off, Odin's gift of three lives and Thor's three curses, the sacrifice of King Vikar with the reed that became a spear, the crimes and the old age, the death by Hather's hand for pay, Saxo's Starcatherus and Gautreks saga, Dumézil's Stakes of the Warrior"),
 ("norse","ragnar_lodbrok","Ragnar Lodbrok","the hairy-breeches viking of Ragnars saga, the killing of the serpent for Thora, Aslaug the daughter of Sigurd, the sons (Ivar the Boneless, Bjorn Ironside, Sigurd Snake-in-the-Eye), the death in Ella's snake pit and the Krákumál, the historicity question (the 845 Paris raider Reginheri), the Great Heathen Army, the TV series as reception"),
 ("norse","hervor","Hervör","the shieldmaiden who raised her father Angantyr from his barrow on Samsey to claim the cursed sword Tyrfing (the Waking of Angantyr, Hervarar saga), the second Hervör who died in battle against the Huns, the riddles of Gestumblindi in the same saga, Tolkien's Rohan and the saga"),
 ("norse","helgi_hundingsbane","Helgi Hundingsbane","the hero of the two Helgi lays of the Poetic Edda, the valkyrie Sigrun's love, the killing of Hunding and of Hodbrodd, the death by Dag's spear and the return from the barrow to lie with Sigrun one night, the reincarnation as Helgi Haddingjaskati, the Helgi Hjorvardsson doublet"),
 ("norse","dietrich_von_bern","Dietrich von Bern","Theoderic the Great made hero: the exile at Etzel's court, the Nibelungenlied's Dietrich who captures Hagen and Gunther, the Rabenschlacht and the Dietrichs Flucht, the Thidrekssaga's whole life, the fight with the dwarf Laurin and the giants, the fire-breath, the ride to hell on the black horse (the Christian ending), the Rök stone"),
 ("norse","hagen","Hagen (Högni)","the grim vassal who killed Siegfried at the spring and sank the hoard in the Rhine, the Nibelungenlied's Hagen against the Edda's Högni (Gunnar's brother whose heart was cut out), the last stand at Etzel's hall and Kriemhild's stroke, the mermaids' prophecy at the Danube, Wagner's Hagen"),
 ("norse","gunnar","Gunnar (Gunther)","the Burgundian king who won Brynhild by Sigurd's deception, the oath-brother's murder, the snake pit and the harp played with his toes (the Atlakvida and the Oddrun lay), the historical Gundaharius killed by the Huns in 437, the Nibelungenlied's Gunther and Wagner's"),
 ("norse","grettir","Grettir the Strong","the outlaw of Grettis saga: the fight with Glam the revenant and the curse of fear of the dark, the nineteen years of outlawry, the swim from Drangey, the death by sorcery on the island, the Beowulf parallels (Sandhaugar), the saga's date (c. 1320) and its author-question"),
 ("norse","egil","Egil Skallagrimsson","the poet-viking of Egils saga: the first killing at seven, the head-ransom before Eirik Bloodaxe at York, the runes against the poisoned drink, the Sonatorrek for his drowned son, the silver hidden in old age, the skull too hard for an axe (Paget's disease as diagnosis), Snorri as the probable author"),
 # ---------------- PERSIAN ----------------
 ("persian","rostam","Rostam","the champion of Sistan, son of Zal and Rudabeh, born by caesarean with the Simurgh's help, the horse Rakhsh, the seven labours (the Haft Khan), the killing of the White Div, the tragic combat with his son Sohrab, the rescue of Kay Kavus, the fight with Esfandiyar and the arrow of the Simurgh, the death in the pit dug by his half-brother Shaghad, the Sogdian Rustam fragments and the Panjikent murals as the pre-Ferdowsi evidence, Arnold's Sohrab and Rustum"),
 ("persian","sohrab","Sohrab","the son Rostam did not know, born of Tahmineh in Samangan, the armband, the three combats and the death by his father's hand, the antidote refused by Kay Kavus, the Shahnameh's central tragedy and its performances (the naqqali and the ta'ziyeh-like readings), the Sohrab of Matthew Arnold"),
 ("persian","zal","Zal","the white-haired child exposed on the Alburz and raised by the Simurgh, the feather that summons her, the love of Rudabeh (the hair let down from the tower), the father of Rostam, the wise old man of Sistan who outlives his son, the albino reading"),
 ("persian","siyavash","Siyavash","the prince falsely accused by his stepmother Sudabeh, the ordeal of fire, the exile to Turan and Afrasiyab's court, Farangis, the city Siyavashgird, the murder and the plant that grew from his blood, the mourning of Siyavash (the Sug-e Siyavash, Narshakhi's Bukhara) and the Panjikent frescoes, the Central Asian cult of the dying prince"),
 ("persian","esfandiyar","Esfandiyar","the bronze-bodied prince of Goshtasp, the champion of the new Zoroastrian faith, his own seven labours, the imprisonment by his father, the mission to bind Rostam and the death by the double-pointed tamarisk arrow guided by the Simurgh, the invulnerability except the eyes (the Achilles comparison), the Avestan Spentodata"),
 ("persian","kaveh","Kaveh the Blacksmith","the smith who raised his leather apron on a spear against Zahhak and led the people to Fereydun, the Derafsh-e Kaviani that became the Sasanian royal banner, the Kaveh of the Iranian and Kurdish nationalisms (the Newroz fire, the Kaveh journal of Berlin 1916), the smith's revolt as political myth"),
 ("persian","fereydun","Fereydun (Thraetaona)","the Avestan Thraetaona who slew Azhi Dahaka, the Shahnameh's Fereydun who chained Zahhak on Damavand, the cow Barmayeh, the division of the world among his three sons and the murder of Iraj by Salm and Tur (the origin of the Iran-Turan war), the mace with the ox-head, the Vedic Trita as cognate"),
 ("persian","kay_khosrow","Kay Khosrow","the son of Siyavash raised in Turan, the crossing of the Oxus, the long war and the killing of Afrasiyab, the just king who renounced the throne and walked into the mountain snow to vanish (the occultation), the Avestan Kavi Haosravah, the cup of Kay Khosrow (the world-showing goblet) and the Grail comparisons, the Sufi readings"),
 ("persian","arash","Arash the Archer","the archer who shot the arrow from Damavand that fixed the border of Iran and Turan and died in the effort, the Avestan Erekhsha of Yasht 8, the Tirgan festival, al-Biruni's account, the Arash of modern Iranian poetry (Siavash Kasrai's Arash-e Kamangir, 1959)"),
 ("persian","garshasp","Garshasp (Keresaspa)","the Avestan dragon-slayer Keresaspa who cooked his meal on the back of the horned serpent, the killer of Gandarewa and Snavidhka, the sin that kept him from paradise and the end-time role of killing Azhi Dahaka, the Garshaspnameh of Asadi Tusi (1066), the ancestor of Rostam's line"),
 # ---------------- HINDU ----------------
 ("hindu","arjuna","Arjuna","the third Pandava, son of Indra, the archer of the fish's eye, Draupadi won, the exile and the Pashupata weapon from Shiva (the Kirata), the year as Brihannala, Krishna as charioteer and the Bhagavad Gita, the killing of Karna and Bhishma's fall, the Ashvamedha, the fall on the Himalaya, the Arjuna of Java and Bali (Arjunawiwaha) and of the wayang"),
 ("hindu","bhima","Bhima","the second Pandava, son of Vayu, the strongest, Hidimba and Ghatotkacha, the killing of Bakasura, Kichaka and Jarasandha, the vow to drink Duhshasana's blood and break Duryodhana's thigh, the Bhima of the folk cults (Bhimashankar, the Bhima of the Garhwal), the wrestlers' Bhima"),
 ("hindu","yudhishthira","Yudhishthira","the eldest Pandava, son of Dharma, the king who lost everything at dice, the Yaksha's questions at the lake, the one lie about Ashvatthama, the Rajasuya and the horse sacrifice, the last walk to the Himalaya with the dog and the ascent in the body, the hell shown to him, the dharma-king problem in the scholarship"),
 ("hindu","karna","Karna","the son of Kunti and Surya set adrift in a basket, raised by the charioteer, the armour and earrings born with him and given away to Indra, the friend of Duryodhana, the curses of Parashurama and the Brahmin, the wheel stuck in the mud and the death by Arjuna's arrow, the Karna of Tagore and the modern novels (Mrityunjay), the tragic hero reading"),
 ("hindu","bhishma","Bhishma","the son of Ganga and Shantanu, the terrible vow of celibacy, the abduction of the Kashi princesses and Amba's revenge as Shikhandi, the grandsire on the bed of arrows waiting for the sun's northern turn, the Shanti and Anushasana Parvas spoken from the arrows, the Bhishma Ashtami"),
 ("hindu","drona","Drona","the Brahmin teacher of the Kauravas and Pandavas, the pot-born, the grudge against Drupada, Ekalavya's thumb, the death by the lie about Ashvatthama and Dhrishtadyumna's sword, the guru-dakshina ethics in the modern debate (Ekalavya as Dalit hero)"),
 ("hindu","abhimanyu","Abhimanyu","the son of Arjuna and Subhadra who learned to enter the chakravyuha in the womb and not to leave it, the sixteen-year-old killed by six warriors together, Uttara and the posthumous Parikshit, the Abhimanyu of the Marathi and Kannada folk plays"),
 ("hindu","draupadi","Draupadi","the fire-born wife of the five Pandavas, the dice and the disrobing and Krishna's endless cloth, the vow of the unbound hair, Kichaka, the Draupadi cult of Tamil Nadu with the fire-walking (Hiltebeitel's two volumes), the Draupadi of the Terukkuttu and of the modern feminist retellings (Yajnaseni, The Palace of Illusions)"),
 ("hindu","duryodhana","Duryodhana","the eldest Kaurava, the jealousy and the dice, the lacquer house, the refusal of five villages, the thigh broken by Bhima against the rules, the Duryodhana who has temples (Har-ki-Doon, Kerala's Poruvazhy Peruviruthy Malanada), the sympathetic Duryodhana of Bhasa's Urubhanga and of the modern readings"),
 ("hindu","ashwatthama","Ashwatthama","the son of Drona with the jewel in his forehead, the night raid on the sleeping camp and the killing of the Pandava children, the Brahmastra against the unborn Parikshit, the curse of immortal wandering with the wound, the Chiranjivi, the sightings in the Narmada forests as living legend, the Asirgarh fort"),
 # ---------------- CELTIC ----------------
 ("celtic","cu_chulainn","Cú Chulainn","the hound of Culann, son of Lugh, the boyhood deeds, the ríastrad warp-spasm, the Táin's single combats at the ford (Ferdiad), the death tied to the standing stone with the raven on his shoulder, Emer and Fand, the gae bolga, Scáthach in Scotland, the Cú Chulainn of the GPO statue and of Yeats, the Ulster loyalist and republican uses"),
 ("celtic","finn_mac_cumhaill","Finn mac Cumhaill","the leader of the Fianna, the salmon of knowledge and the thumb, Sadhbh and Oisín, the pursuit of Diarmuid and Gráinne, the death at the Boyne (or the sleeping hero under the hill), the Acallam, the Giant's Causeway Finn of the folk, Macpherson's Fingal and the Ossian controversy, the Fenians named for him"),
 ("celtic","oisin","Oisín","Finn's son and the poet of the Fianna, the ride to Tír na nÓg with Niamh, the three hundred years and the fall from the horse, the dialogues with St Patrick (the Acallam and the Ossianic lays), Ossian of Macpherson and Napoleon's Ossian, Yeats's Wanderings of Oisin"),
 ("celtic","diarmuid_and_grainne","Diarmuid and Gráinne","the love-spot and the geis laid at Finn's wedding feast, the flight through Ireland (the dolmens as their beds), the years of pursuit, the boar of Ben Bulben and Finn's hands that let the water fall, the Tristan and Isolde comparison, the Tóruigheacht text"),
 ("celtic","conall_cernach","Conall Cernach","the Ulster warrior who avenged Cú Chulainn and carried Lugaid's head, the Cattle Raid of Fraech, the Conall of the Táin Bó Fraích and the Da Derga hostel, the Cernunnos name-question, the Scottish and Ulster genealogies claiming him"),
 ("celtic","fergus_mac_roich","Fergus mac Róich","the exiled king of Ulster who fought for Medb in the Táin, the sword Caladbolg that cut the hilltops, the lover of Medb caught by Ailill, the Fergus whose ghost recited the lost Táin to the poet (the finding of the Táin), the death by Lugaid's spear while swimming"),
 ("celtic","medb","Medb","the queen of Connacht who started the Táin for the Brown Bull, the pillow talk with Ailill, the lovers 'never without one man in the shadow of another', the sovereignty goddess behind the queen (the Medb of Tara who married nine kings), the death by a hard cheese from a sling at Inis Clothrann, Knocknarea's cairn"),
 ("celtic","deirdre","Deirdre","Deirdre of the Sorrows: the prophecy at her birth, Naoise and the flight to Scotland, Conchobar's treachery and the death of the sons of Uisliu, the year without a smile and the death against the rock (the Exile of the Sons of Uisliu, the Longes mac nUislenn), Synge's and Yeats's Deirdres, the Deirdre of the Ulster revival"),
 ("celtic","taliesin","Taliesin","the sixth-century bard of Urien Rheged behind the Book of Taliesin, and the legendary Taliesin born of Ceridwen's cauldron (Gwion Bach, the Hanes Taliesin), the boy who shamed Maelgwn's bards, the prophetic poems and Cad Goddeu, Ifor Williams's separation of the historical from the legendary, the Taliesin of the Welsh revival and of Frank Lloyd Wright's house"),
 ("celtic","culhwch","Culhwch","the hero of Culhwch ac Olwen, the earliest Arthurian tale: the stepmother's curse, the impossible tasks of Ysbaddaden the giant, the hunt of the boar Twrch Trwyth across Wales and Cornwall, the catalogue of Arthur's court, the Mabon and Olwen, the oldest layer of the Arthur legend"),
 # ---------------- SLAVIC ----------------
 ("slavic","ilya_muromets","Ilya Muromets","the peasant's son who sat thirty years and was healed by the pilgrims, the horse, Nightingale the Robber, the defence of Kiev and the quarrel with Prince Vladimir, the fight with his own son, the turning to stone, the monk Ilya of the Kiev Caves (the relics, canonized 1643) as the historical claimant, Vasnetsov's Bogatyrs, the Soviet Ilya"),
 ("slavic","dobrynya_nikitich","Dobrynya Nikitich","the courtly bogatyr who killed the dragon Zmey Gorynych and rescued Zabava, the diplomat and the harpist, the wife almost lost to Alyosha, the historical Dobrynya, Vladimir the Great's uncle, as the shadow, the Novgorod baptism 'by fire and sword'"),
 ("slavic","alyosha_popovich","Alyosha Popovich","the priest's son, the trickster bogatyr who killed Tugarin the dragon-man by a ruse, the seducer who tried to marry Dobrynya's wife, the Rostov Alexander Popovich of the chronicles who died at the Kalka (1223), the youngest of Vasnetsov's three"),
 ("slavic","sadko","Sadko","the Novgorod gusli player who won the wager with the Sea King and became a merchant, the storm and the descent to the Sea King's palace, the dance that wrecked the ships, St Nicholas's intervention, the Novgorod cycle's merchant hero, Rimsky-Korsakov's opera (1898) and Ptushko's film"),
 ("slavic","svyatogor","Svyatogor","the giant bogatyr too heavy for the earth to bear, the bag with the earth's weight he could not lift, the coffin that fit him and the lid that would not open, the strength breathed into Ilya, the older layer of the byliny and the Indo-European giant"),
 ("slavic","volkh_vseslavyevich","Volkh Vseslavyevich","the werewolf sorcerer-prince born of a serpent, the shape-shifter who led his druzhina against the Indian kingdom, the Vseslav of Polotsk (the wolf-prince of the Igor Tale) behind him, the shamanic and the Indo-European werewolf warrior (Jakobson)"),
 # ---------------- FINNIC ----------------
 ("finnic","vainamoinen","Väinämöinen","the eternal sage born of the Air Maiden after seven hundred years, the singer who sang Joukahainen into the swamp, the kantele from the pike's jaw, the Sampo expedition, the failed courtship of the Maiden of Pohjola, the departure in the copper boat when the child of Marjatta is born (the Kalevala's Christian ending), Agricola's list of 1551, Haavio's study"),
 ("finnic","ilmarinen","Ilmarinen","the eternal smith who forged the sky's vault and the Sampo, the golden bride who was cold, the marriage with the Maiden of Pohjola and her death by Kullervo's cattle, the Sampo raid, the Vedic Tvashtar and the smith-god type, the Ilmarinen of Agricola's list"),
 ("finnic","lemminkainen","Lemminkäinen","the reckless lover, the killing of the master of Pohjola, the descent to Tuonela and the death in the river, the mother who raked the pieces from the water and sang him back to life, Gallen-Kallela's painting (1897), Sibelius's suite, Lönnrot's fusion of several rune-heroes (Kaukomieli, Ahti) into one, say so"),
 ("finnic","kullervo","Kullervo","the slave-born avenger, the knife broken on the stone in Ilmarinen's wife's bread, the sister seduced unknowing, the war against Untamo, the sword asked whether it would drink guilty blood, Sibelius's Kullervo (1892), Tolkien's Story of Kullervo and Túrin, the Kalevala's darkest cycle"),
 # ---------------- JAPANESE ----------------
 ("japanese","yamato_takeru","Yamato Takeru","the prince who killed his brother and was sent away by his father Keikō, the Kumaso chieftains killed in women's clothing, the grass-cutting sword Kusanagi from Ise, the burning field, Ototachibana's sacrifice in the sea, the death by the mountain god's poison and the white bird that flew from the tomb, the Kojiki against the Nihon Shoki, the Yamato Takeru of the imperial ideology"),
 ("japanese","momotaro","Momotarō","the peach boy of the Edo picture books, the dog, monkey and pheasant, the millet dumplings, the expedition against the oni of Onigashima, the Meiji school reader that fixed the tale (1887), the wartime propaganda Momotarō (the 1945 anime Momotarō: Sacred Sailors), Okayama's claim, Antoni's study"),
 ("japanese","yoshitsune","Minamoto no Yoshitsune","the Genji general of the Genpei war made legend: the childhood at Kurama with the tengu, Benkei at the Gojō bridge, the victories at Ichinotani, Yashima and Dannoura, the flight from his brother Yoritomo, the Ataka barrier (Kanjinchō), the death at Koromogawa (1189), the Gikeiki, the Hōgan-biiki sympathy for the loser, the legend that he became Genghis Khan as documented invention"),
 ("japanese","benkei","Benkei","the warrior monk born after eighteen months with teeth and hair, the thousand swords on the Gojō bridge and the defeat by Yoshitsune, the reading of the false subscription list at Ataka, the standing death at Koromogawa pierced by arrows, the Benkei of Noh (Ataka, Funa Benkei) and Kabuki (Kanjinchō)"),
 ("japanese","kintaro","Kintarō","the golden boy raised by the mountain witch on Ashigara, the sumo with bears, the axe, the recruitment by Minamoto no Raikō as Sakata no Kintoki (one of the four guardian kings who killed Shuten-dōji), the Boys' Day dolls and the candy with his face, the Kintarō of Utamaro"),
 ("japanese","urashima_taro","Urashima Tarō","the fisherman who saved the turtle and spent three days (three hundred years) in the Dragon Palace, the box that must not be opened, the oldest version in the Nihon Shoki (478 CE entry) and the Man'yōshū, the Otogizōshi and the Meiji reader version, the Urashima of relativity jokes and of the Yosano and Ōe uses"),
 # ---------------- MESOPOTAMIAN ----------------
 ("mesopotamian","etana","Etana","the shepherd-king of Kish who flew to heaven on the eagle to fetch the plant of birth, the eagle and the serpent's broken oath, the fall (or not: the tablets break off), the Sumerian King List's Etana as the first king after the flood 'who went up to heaven', the cylinder seals of the flight (Akkadian period), the Old Babylonian, Middle Assyrian and Standard versions"),
 ("mesopotamian","sargon_legend","The Sargon Birth Legend","the Sargon of Akkad of the legend: the priestess mother, the basket of rushes sealed with bitumen on the river, Aqqi the water-drawer, Ishtar's love, the fifty-five years of kingship, the Neo-Assyrian text (the 'autobiography', 7th century), the Moses comparison and its direction, the King of Battle epic (Sargon in Anatolia), the Sumerian Sargon legends (Ur-Zababa's dream), the historical Sargon as the shadow"),
 # ---------------- BIBLICAL ----------------
 ("biblical","adam","Adam","the first man of Genesis 1-5 in its two accounts (the image, the dust and the breath), the naming, the rib, the tree and the expulsion, the 930 years, the Adam of 1 Enoch and the Life of Adam and Eve, the rabbinic Adam (the golem of dust, the giant, Lilith), Paul's second Adam, the Islamic Adam and the angels' prostration, the Adam Kadmon of the Kabbalah (pantheon/abrahamic has that file), Michelangelo's, Milton's"),
 ("biblical","eve","Eve","the mother of all living: the rib and the two accounts, the serpent and the fruit, the curse and the childbirth, Cain, Abel and Seth, the Life of Adam and Eve's penance in the river, the rabbinic Eve and the 'first wife' Lilith tradition, the Church Fathers' Eve (Tertullian's 'gate of the devil') and the Eve-Mary typology, the Islamic Hawwa, the modern feminist readings (Trible, Pagels)"),
 ("biblical","cain_and_abel","Cain and Abel","the first murder: the offerings, the fallen face, the field, the mark, the city of Enoch, the Cainite genealogy (the smiths, the musicians), the Cain of 1 Enoch and Jubilees, Cain as the devil's son in the Gnostic and Jewish legends, the Cainites of Irenaeus, the Islamic Qabil and Habil and the raven, Byron's Cain, Steinbeck's East of Eden, the mark of Cain in the racial readings as documented abuse"),
 ("biblical","enoch","Enoch","the seventh from Adam who walked with God and was not (Genesis 5:24), the 365 years, the scribe of 1 Enoch (the Watchers, the Parables, the Astronomical Book), 2 Enoch's ascent through the heavens, 3 Enoch's transformation into Metatron (pantheon/abrahamic has him), Jude's citation, the Ethiopian canon, the Islamic Idris and the Hermes identification, the Freemasons' Enoch and the Mormon Enoch"),
 ("biblical","nimrod","Nimrod","the mighty hunter before the Lord, the first king (Genesis 10:8-12), the builder of Babel in the rabbinic tradition, the persecutor of Abraham in the furnace (the midrash and the Qur'an's unnamed king), Josephus's tyrant, the Ninurta and Sargon identifications of the scholars, Dante's giant, the Nimrod of Elgar and the hunting word"),
 ("biblical","lot","Lot and his wife","Abraham's nephew, the choice of Sodom, the angels and the mob, the flight, the wife turned to salt and the pillar shown at the Dead Sea (Josephus, the pilgrims, the modern rock), the cave and the daughters (Moab and Ammon), the Lut of the Qur'an, the Lot of the Genesis Rabbah and of the Christian typology"),
 ("biblical","job","Job","the man of Uz, the wager in the heavenly court, the losses, the three friends and Elihu, the voice from the whirlwind and Behemoth and Leviathan (pantheon/abrahamic has both), the restoration, the Testament of Job, the rabbinic debates on whether he existed (b. Bava Batra 15a), the Islamic Ayyub and the spring, Blake's engravings, Jung's Answer to Job, the Job of the Argentine and Latin American essay tradition in one line"),
 ("biblical","jonah","Jonah","the prophet who fled to Tarshish, the storm and the lot, the great fish and the three days, Nineveh's repentance and the gourd, the historical Jonah of 2 Kings 14:25, the book's date and satire question, the Yom Kippur reading, the sign of Jonah in the Gospels, the Islamic Yunus, the Jonah of the catacombs and of Melville's Father Mapple"),
 ("biblical","samson","Samson","the Nazirite of Dan: the lion and the honey, the foxes, the jawbone, the gates of Gaza, Delilah and the hair, the blinding and the mill, the temple pulled down, the solar-hero reading (Shemesh, Beth-Shemesh) and its critics, Samson in the rabbis and the Fathers (the Christ type), Milton's Samson Agonistes, the Samson Option as reception"),
 ("biblical","delilah","Delilah","the woman of the valley of Sorek and the eleven hundred pieces of silver, the three false secrets and the true one, the shearing on her lap, the question of her nation (Philistine? Israelite?) and her fate (the text never says), the rabbinic and patristic Delilah, Saint-Saëns's Dalila, the cinema's Delilah (DeMille), the name as a byword"),
 ("biblical","gideon","Gideon","the least in Manasseh threshing in the winepress, the fleece, the three hundred chosen by how they drank, the trumpets and the jars, Zebah and Zalmunna, the ephod at Ophrah that became a snare, the refusal of the crown and his son Abimelech's usurpation, the Gideons as reception"),
 ("biblical","deborah_and_jael","Deborah and Jael","the prophetess judging under the palm, Barak and the ten thousand, Sisera's chariots at the Kishon, Jael's tent peg through the temple, the Song of Deborah (Judges 5) as one of the oldest Hebrew poems, the mother of Sisera at the window, the Deborah of the rabbis and of the feminist readings, Jael in the Renaissance paintings"),
 ("biblical","judith","Judith","the widow of Bethulia who went to Holofernes's tent and cut off his head, the book's Greek text and its deuterocanonical status, the historical impossibilities as deliberate (Nebuchadnezzar king of Assyria), the Hanukkah connection, the Judith of Donatello, Caravaggio, Artemisia Gentileschi and Klimt, the Judith of the Argentine and Latin American stage in one line"),
 ("biblical","esther","Esther","the orphan queen of Ahasuerus, Vashti's refusal, Mordecai and Haman, the fast and the unsummoned approach, the gallows, Purim and the Megillah, the book without God's name, the Greek additions, the historicity question (Xerxes, the Persian names, the Ishtar-Marduk theory), the Esther of the Marranos (the fast of Esther as crypto-Jewish rite), Racine's Esther"),
 ("biblical","daniel","Daniel","the exile at Nebuchadnezzar's court, the dreams read, the fiery furnace of his three friends, Belshazzar's feast and the writing on the wall, the lions' den, the visions of the four beasts and the seventy weeks, the book's Aramaic and Hebrew and its Maccabean date, Susanna and Bel and the Dragon, the Daniel of Ezekiel 14 (Danel of Ugarit?), the apocalyptic afterlife (the four kingdoms, the millenarians)"),
 ("biblical","joshua","Joshua","Moses's minister and successor, the spies and Rahab, the Jordan stopped, Jericho's walls and the trumpets, the sun stood still at Gibeon, the conquest and the herem (the Canaanite genocide problem in the modern ethics), the covenant at Shechem, the archaeology of Jericho and Ai against the book (Kenyon, Finkelstein), the Islamic Yusha, the Joshua of the spirituals"),
 ("biblical","elijah","Elijah","the Tishbite: the ravens at Cherith, the widow of Zarephath, the contest on Carmel and the fire, Jezebel's threat and the still small voice at Horeb, Naboth's vineyard, the mantle and the chariot of fire, the return promised (Malachi 3:23), the cup at the Seder and the chair at the circumcision, the Elijah of the Talmudic stories and the Kabbalah, the Carmelites' claim, the Transfiguration, the Islamic Ilyas and al-Khidr, Mendelssohn's oratorio"),
 ("biblical","solomon","Solomon","the son of David and Bathsheba, the wisdom asked for at Gibeon, the judgment of the two mothers, the Temple, the Queen of Sheba's visit (the atlas has her), the thousand wives and the turning to other gods, the Song of Songs and Ecclesiastes attributed, the Solomon of the Testament of Solomon and the ring that bound the demons (pantheon/goetia's ancestor), the Islamic Sulayman with the jinn and the hoopoe, the Ethiopian Menelik, the Seal of Solomon, the archaeology of the 'Solomonic' gates and the minimalist debate"),
 ("biblical","jacob","Jacob","the heel-grasper who bought the birthright and stole the blessing, the ladder at Bethel, Laban and the two wives and the speckled sheep, the wrestling at the Jabbok and the name Israel, the reunion with Esau, the sons and the coat, the descent to Egypt and the blessings, the burial at Machpelah (Abraham's cave in the atlas), the rabbinic Jacob who studied Torah, the Islamic Ya'qub, Jacob's ladder in Genesis Rabbah and the Kabbalah"),
 ("biblical","joseph_the_dreamer","Joseph the Dreamer","the coat, the dreams and the pit, the Ishmaelites and Potiphar's wife, the prison and the dreams of the butler and the baker, Pharaoh's dreams and the seven years, the brothers and the cup, the reconciliation, the bones carried out of Egypt, the Joseph of the Genesis Rabbah and of Surah 12 (the most beautiful of stories, Zulaykha), Thomas Mann's Joseph and His Brothers, the Joseph of Andrew Lloyd Webber as reception"),
 # ---------------- YORUBA ----------------
 ("yoruba","oranmiyan","Oranmiyan (Oranyan)","the son of Oduduwa (or of two fathers, the story of the half-and-half body), the founder of Oyo and the first Alaafin, the sent king of Benin who fathered Eweka and went home, the Oranmiyan staff (the Opa Oranmiyan, the granite monolith at Ife with its iron nails), the horse and the grave that opened, Johnson's History of the Yorubas and the Benin chronicles"),
 ("yoruba","moremi_ajasoro","Moremi Ajasoro","the Ife queen who let herself be captured by the Igbo raiders (the Ugbo), learned that the raiders' costumes were raffia and could be burned, returned and saved Ife, and sacrificed her son Oluorogbo to the river Esimirin as promised, the Edi festival, the Moremi shrine at Ife and the 42-foot statue of 2016, the Moremi of the Nigerian stage and of the women's associations"),
]

SIGNS = {}
FOLDER = {}
for folder, slug, name, pointers in ROSTER:
    assert slug not in SIGNS, f"duplicate slug {slug}"
    label, sources = TRADITIONS[folder]
    SIGNS[slug] = (name, f"{label} heroes", pointers, folder, sources)
    FOLDER[slug] = folder

ORDER = [slug for folder in TRADITIONS for (f, slug, _, _) in ROSTER if f == folder]


def out_path(slug):
    return f"{FOLDER[slug]}/{slug}.md"


if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    for slug, (name, status, pointers, folder, sources) in SIGNS.items():
        text = f"""# {name}: research brief

Heroes collection, Anthony 2026-09-17, symbols/heroes/{folder}/. Appended to
PROMPT_TEMPLATE_HEROES.md by tools/codex_dossier_set.py.

---

HERO. {name} ({status}). State at the top the figure's class as the tradition classes it (mortal
hero, demigod, heroized dead with cult, culture hero, epic king) and the earliest secure attestation.

THREADS TO PULL, each to be verified against the sources and dated: {pointers}.

WHERE THE SOURCES ARE for this tradition: {sources}.

STANCE. Legend as fully as fact; nothing discarded for being unprovable, everything labeled.
Where a thread above names a dispute, present both sides with their evidence. Every documented
interaction with another named god or hero gets its own line (the other figure, the nature of the
interaction, the source and date), since sibling dossiers exist for the gods of this tradition in
symbols/pantheon and for the other heroes here, and the files cross-reference by name. Absence of
evidence is a finding.
"""
        open(os.path.join(OUT, f"{slug}.brief.md"), "w").write(text)
    from collections import Counter
    print("wrote", len(SIGNS), "briefs:", dict(Counter(FOLDER.values())))
