#!/usr/bin/env python3
"""Write one brief per Bode constellation into working/bode/briefs/. The set is the Bode
collection on chain (109 groups) less the Winter Triangle, with Serpens counted once and the
twelve zodiac figures excluded (they have working/zodiac): 95 constellations, 76 kept by the
IAU and 19 abolished."""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "briefs")

P48 = "one of Ptolemy's 48 (Almagest, c. 150 CE), kept by the IAU in 1922"
BAY = "one of the twelve southern constellations of Keyser and de Houtman, first on Plancius's globe of 1598 and in Bayer's Uranometria (1603), kept by the IAU"
HEV = "introduced by Hevelius, Firmamentum Sobiescianum (1690), kept by the IAU"
LAC = "introduced by Lacaille from the Cape of Good Hope (1751-52, published 1756), kept by the IAU"

SIGNS = {
 # ---- the ancient 48 (less the zodiac) ----
 "andromeda": ("Andromeda", P48, "the chained princess of Ethiopia, daughter of Cepheus and Cassiopeia, saved by Perseus from Cetus (Eratosthenes, Hyginus, Ovid Met. 4, Apollodorus 2.4); the whole royal family in the sky; the Great Nebula M31 and its history from al-Sufi's 'little cloud' (964) to Hubble's 1923-25 Cepheids; Alpheratz shared with Pegasus's Square until 1930; Almach the double; Andromeda as Perseus's bride at Joppa (Pliny's chains at Jaffa); the Perseids' neighbor; Schiller's Sepulchrum Christi"),
 "aquila": ("Aquila", P48, "the eagle of Zeus, bearer of the thunderbolt, abductor of Ganymede (Eratosthenes 30, Hyginus 2.16, Ovid Met. 10), the eagle that ate Prometheus's liver; Altair the flying eagle, the Summer Triangle; Antinous, Hadrian's boy, carried in its talons from 132 CE to the IAU (Ptolemy's Antinous, Bode's plate); the Babylonian Eagle MUL.TI8.MUSHEN; the Chinese Cowherd Niulang and the Weaver across the river; Schiller's St Catherine; the Aquilid claims; the 389 CE nova; the first pulsar? (no: Vulpecula); the Vega-Altair legends"),
 "ara": ("Ara", P48, "the altar of the gods on which Zeus and the Olympians swore before the war with the Titans (Eratosthenes 39, Hyginus 2.39), the altar of Chiron, the altar of Noah in Schiller; Ptolemy's Thymiaterion the censer; the smoke as the Milky Way; the southern altar's inversion on the plates (Bayer draws it upside down); the Ara cluster NGC 6397; the Bedouin sky in its stars"),
 "auriga": ("Auriga", P48, "the charioteer: Erichthonius the lame inventor of the four-horse chariot (Eratosthenes 13, Hyginus 2.13), Myrtilus, Phaethon, Hippolytus; Capella the she-goat Amalthea and the Kids on the charioteer's arm, the goat nursing Zeus; the star Elnath shared with Taurus until 1930; the Babylonian Crook GAM; the Kids as a weather sign in Aratus, Theocritus, Horace; Schiller's St Jerome; epsilon Aurigae's eclipses; the Flaming Star Nebula"),
 "bootes": ("Boötes", P48, "the ploughman or herdsman driving the Bears, Arctophylax; Icarius who received the vine from Dionysus and was killed by the shepherds, with Erigone (Virgo) and the dog Maera (Hyginus 2.4, Eratosthenes 8); Arcas son of Callisto; Philomelus inventor of the wagon; Arcturus the bear-guard, the brightest of the northern sky, in Job and Hesiod's Works and Days as a season marker, in the 1933 Chicago fair's opening; the Quadrans Muralis in its stars (Bode's abolished quadrant, the Quadrantid meteors); Schiller's St Sylvester"),
 "canis_major": ("Canis Major", P48, "Laelaps the dog that always caught its prey, given by Zeus to Europa, to Minos, to Procris, to Cephalus, turned to stone with the Teumessian fox (Ovid Met. 7, Hyginus 2.35), or Orion's dog; Sirius the Dog Star, the Egyptian Sopdet/Sothis and the Nile flood and the Sothic cycle, the Greek dog days and the sacrifices of red dogs, Homer's Iliad 22 (Achilles as the Dog Star); the color of Sirius controversy (Ptolemy's 'reddish'); the Dogon and the Sirius B claim (Temple 1976) and its refutation; Sirius B's discovery 1862; Schiller's St David; the Chinese Celestial Wolf; the star of Isis at Dendera"),
 "canis_minor": ("Canis Minor", P48, "Procyon, 'before the dog', rising before Sirius; Maera the dog of Icarius and Erigone (Hyginus 2.4), or Helen's dog, or the Teumessian fox; Ptolemy's Prokyon as a two-star figure; the Babylonian Shukudu? (no: that is Sirius) and the Twins' dog; Schiller's Lamb of the Passover; Procyon B and Bessel's 1844 prediction; the Egyptian Anubis readings of the two dogs"),
 "cassiopeia": ("Cassiopeia", P48, "the boasting queen of Ethiopia, mother of Andromeda, who claimed to outshine the Nereids, set in the sky upside down in her chair as punishment (Eratosthenes 16, Hyginus 2.10, Ovid Met. 4); the W and the Chair; Tycho's supernova of 1572 in it, De nova stella, the death of the Aristotelian sky; Cassiopeia A the radio source and the unseen supernova of c. 1680 (Flamsteed's 3 Cas?); Schedar, Caph, the Bedouin 'tinted hand'; the Arabic Dhat al-Kursi the lady in the chair; Schiller's Mary Magdalene; the Chinese Wang Liang"),
 "centaurus": ("Centaurus", P48, "Chiron the wise centaur, teacher of Achilles, Jason, Asclepius, wounded by Heracles's arrow and set in the sky (Eratosthenes 40, Hyginus 2.38), or Pholus; the centaur holding the Beast (Lupus) toward the altar; Alpha Centauri and Proxima, the nearest stars, Rigil Kentaurus, Hadar; Omega Centauri the great cluster, Halley 1677; Centaurus A the radio galaxy; the Southern Cross once its hind legs (Ptolemy), cut out by Plancius and Bayer; the Bedouin sky; Schiller's Abraham and Isaac; the 1006 supernova in Lupus next door"),
 "cepheus": ("Cepheus", P48, "the king of Ethiopia, husband of Cassiopeia, father of Andromeda, son of Belus (Hyginus 2.9, Apollodorus 2.4); the Ethiopia question (which Ethiopia, Joppa or the Nile); Delta Cephei the prototype Cepheid variable (Goodricke 1784) and Leavitt's law; Mu Cephei Herschel's Garnet Star; Alderamin the right arm; the pole star to come (Alrai, Alderamin); Schiller's St Stephen; the Chinese Zaofu the charioteer; the Bedouin shepherd and sheep"),
 "cetus": ("Cetus", P48, "the sea monster sent by Poseidon to devour Andromeda, slain by Perseus (Ovid Met. 4, Hyginus 2.31), the whale of Jonah in Schiller and in the sailors' sky; Mira the Wonderful, the first periodic variable (Fabricius 1596, Holwarda 1638), and Mira's tail; Deneb Kaitos, Menkar; Tau Ceti and Ozma; the Babylonian sea monster Tiamat readings; the Ketos of Joppa and its bones shown at Rome by Scaurus (Pliny 9.11); Bode's plate; the Cetus-Pisces border and the vernal point"),
 "corona_borealis": ("Corona Borealis", P48, "the crown of Ariadne, given by Dionysus at their wedding and set in the sky (Eratosthenes 5, Hyginus 2.5, Ovid Met. 8 and Fasti 3), made by Hephaestus, or Theseus's crown from Amphitrite; Alphecca/Gemma; T Coronae Borealis the recurrent nova (1866, 1946, the 2024-25 watch); the Blaze Star; Corona as the Camp of the Boors in Bedouin sky (the broken bowl); the Cheyenne and Shawnee crowns; Schiller's Crown of Thorns; the 'northern crown' of the Welsh Caer Arianrhod"),
 "corvus": ("Corvus", P48, "Apollo's crow sent for water, dawdling at the fig tree, returning with the Hydra as excuse, punished with thirst and set beside the Cup it can never reach (Eratosthenes 41, Hyginus 2.40, Ovid Fasti 2.243); the crow that told on Coronis; the Babylonian Raven MUL.UGA.MUSHEN on the Hydra's tail; Algorab, Gienah; the Antennae galaxies; Schiller's Ark of the Covenant; the Sail (Spica's pointer); the Chinese Chariot"),
 "crater": ("Crater", P48, "the cup of Apollo in the crow story (Ovid Fasti 2), the cup of Icarius, the mixing bowl of Dionysus, the cup of Mastusius (Hyginus 2.40); Alkes; on the Hydra's back with Corvus; Schiller's Ark of the Covenant (with Corvus); the Chinese Wings mansion; the Arabic al-Ma'laf the manger"),
 "cygnus": ("Cygnus", P48, "the swan: Zeus as the swan of Leda, father of Helen and Polydeuces (Eratosthenes 25, Hyginus 2.8, Ovid Met. 6), Cycnus the friend of Phaethon turned swan by the Eridanus (Ovid Met. 2), Orpheus as a swan beside his lyre; Ptolemy's Ornis the bird; Deneb and the Northern Cross, Albireo the double, the Summer Triangle; Cygnus X-1 the first black hole (the Hawking-Thorne bet); the Kepler field; the 1600 nova P Cygni; the North America Nebula; Schiller's Cross with St Helena; the Bedouin 'hen'; the Chinese Heavenly Ford across the river"),
 "delphinus": ("Delphinus", P48, "the dolphin that found Amphitrite for Poseidon (Eratosthenes 31, Hyginus 2.17), the dolphin that saved Arion of Lesbos (Herodotus 1.23-24, Hyginus 2.17); Job's Coffin; Sualocin and Rotanev, Niccolò Cacciatore's name spelled backwards on the Palermo catalogue of 1814, the only stars named for a living assistant by a trick; the Bedouin camel; Schiller's Water Jar of Cana; the 1967 nova HR Delphini"),
 "draco": ("Draco", P48, "Ladon the dragon of the Hesperides killed by Heracles (Eratosthenes 3, Hyginus 2.3, Apollodorus 2.5), or the dragon Athena threw into the sky in the war of the giants, or the Python; Thuban the pole star of the pyramid builders (c. 2800 BCE) and the Great Pyramid's shafts; Eltanin and Bradley's discovery of aberration (1725-28); the Cat's Eye Nebula; the Babylonian dragon of Marduk; the Chinese Purple Enclosure's dragon; Schiller's Holy Innocents; the Draconids; the coils between the Bears in Aratus"),
 "equuleus": ("Equuleus", P48, "the Little Horse, the second-smallest constellation, Ptolemy's Hippou protome the horse's forepart, absent from Aratus; Celeris the brother of Pegasus given to Castor (Hyginus 2.18), or Cyllarus, or Hippe the daughter of Chiron turned to a horse; Kitalpha 'the piece of the horse'; Schiller's Rose of Sharon; the Arabic al-Faras al-Awwal; the dispute over whether Hipparchus invented it"),
 "eridanus": ("Eridanus", P48, "the river into which Phaethon fell, the Po or the Rhône or the Nile, where Cycnus mourned and the Heliades wept amber (Ovid Met. 2, Hyginus 2.32, Eratosthenes 37); Ptolemy's Potamos; the Babylonian river; Achernar 'the end of the river', the second brightest of the south, unseen by Ptolemy and added by Bayer; Cursa, Zaurak; Epsilon Eridani and the Ozma search; Schiller's Red Sea crossing; the Bedouin ostriches; the Egyptian Nile reading; the star-of-Eudoxus dispute (Ptolemy's Eridanus ended at Acamar)"),
 "hercules": ("Hercules", P48, "the Kneeler, Engonasin, whom Aratus would not name, identified as Heracles by Eratosthenes (4) and Hyginus (2.6): kneeling on Draco's head at the garden of the Hesperides, or Theseus lifting the stone, or Orpheus, or Thamyris; the Twelve Labors as a sky map; Rasalgethi the kneeler's head; the Keystone and M13 with the 1974 Arecibo message; the Hercules cluster of galaxies; the solar apex, where the Sun is heading; Schiller's Three Magi; the Chinese Heavenly Market; Bode's plate with the club and the lion skin; Cerberus in his hand (Bode's abolished constellation, separate dossier)"),
 "hydra": ("Hydra", P48, "the Lernaean hydra of the second labor, or the water-snake of the Corvus and Crater story (Eratosthenes 41, Hyginus 2.40); the longest constellation; Alphard the solitary one; the Babylonian serpent MUSH (Ningishzida's beast) across the same stars; the Hydra as the celestial equator of 2800 BCE; the 'Sea of Cats' in Bedouin sky; Felis the cat once on its back (Lalande, abolished, separate dossier); Schiller's River Jordan; M83, the Ghost of Jupiter; TW Hydrae"),
 "lepus": ("Lepus", P48, "the hare at Orion's feet, hunted by his dogs, put in the sky for its speed or its fertility (Eratosthenes 34, Hyginus 2.33), the hares of Leros that overran the island; Arneb 'the hare'; Hind's Crimson Star R Leporis; M79; the Bedouin 'throne of the giant' (al-Jawza's chair) in the same stars; the Egyptian boat of Osiris reading; Schiller's Gideon's Fleece; the Chinese Toilet"),
 "lupus": ("Lupus", P48, "Ptolemy's Therion the Beast, held by the Centaur on a pole toward the Altar, a wolf only from the Renaissance; Lycaon the Arcadian king turned wolf by Zeus (Ovid Met. 1) as a late identification; the Babylonian Mad Dog UR.IDIM in the same stars; the supernova of 1006, the brightest in recorded history, seen from St Gall to Cairo (Ali ibn Ridwan) to China; Schiller's Benjamin; the Bedouin sky; no named bright star, Men"),
 "lyra": ("Lyra", P48, "the lyre of Orpheus, invented by Hermes from a tortoise shell, given to Apollo, to Orpheus, placed in the sky by the Muses after the Maenads tore him apart (Eratosthenes 24, Hyginus 2.7, Ovid Met. 11); Vega the falling eagle/vulture (al-Nasr al-Waqi), the pole star of 12,000 BCE and 14,000 CE, the first star photographed (1850) and the zero of the magnitude scale; the Ring Nebula M57; Beta Lyrae; Epsilon Lyrae the double-double; the Lyrids and the 687 BCE Chinese record; the Vega-Altair legend; Schiller's Manger; the Vulture Cadens of the Arabs"),
 "ophiuchus": ("Ophiuchus", P48, "the Serpent-bearer, Asclepius the healer, son of Apollo and Coronis, taught by Chiron, who raised the dead (Hippolytus, Glaucus) and was struck down by Zeus at Hades's complaint, set in the sky with his serpent (Eratosthenes 6, Hyginus 2.14, Ovid Met. 15), or Laocoön, or Phorbas, or Triopas; the Babylonian sitting god; Rasalhague; Barnard's Star; Kepler's supernova of 1604 in its foot; the rho Ophiuchi clouds; the thirteenth sign argument in full (the ecliptic crossing since Delporte 1930, the 1995 Mitton episode, 2011, 2016 NASA, the sidereal astrologers' answers); Schiller's St Benedict; the rod of Asclepius; the Chinese Heavenly Market"),
 "orion": ("Orion", P48, "the giant hunter, son of Poseidon or born from the bull's hide (Hyginus 2.34, Eratosthenes 32), Merope and Oenopion's blinding, Eos, the scorpion sent by Gaia or Artemis, Artemis's arrow and the sea; Homer's Iliad 18 and Odyssey 5 and 11; Hesiod's harvest markers; the Babylonian True Shepherd of Anu (SIPA.ZI.AN.NA) and Gilgamesh readings; the Egyptian Sah as Osiris, the pyramid-alignment claim (Bauval) and its critics; al-Sufi's al-Jawza (on chain already, cite it); Betelgeuse's 2019-20 dimming and its supernova watch, Rigel, Bellatrix, the Belt (the Three Kings, the Three Marys), the Sword and M42 (Huygens 1656), the Horsehead, Barnard's Loop; the Orionids from Halley's comet; Schiller's St Joseph; the Chinese Shen mansion; Orion in Job and Amos; the Aboriginal Julpan canoe; the Maya hearthstones"),
 "pegasus": ("Pegasus", P48, "the winged horse born from Medusa's blood, tamer of Bellerophon, striker of the Hippocrene spring, bearer of Zeus's thunderbolt (Hesiod Theog., Eratosthenes 18, Hyginus 2.18, Ovid Met. 4-5); Ptolemy's Hippos drawn without wings and only the front half; the Great Square with Alpheratz taken by Andromeda; Enif, Scheat, Markab; 51 Pegasi b, the first exoplanet around a sun-like star (1995); M15; Schiller's Archangel Gabriel; the Babylonian Field IKU; the Chinese Encampment and Wall; the Arabic 'the horse' and the Bedouin bucket"),
 "perseus": ("Perseus", P48, "the hero who cut off Medusa's head with Athena's shield and Hermes's sandals, saved Andromeda, turned Polydectes to stone (Apollodorus 2.4, Ovid Met. 4-5, Hyginus 2.12, Eratosthenes 22); Algol the Demon's Head, the winking star, Goodricke's 1782 eclipse explanation, the Egyptian Calendar of Lucky and Unlucky Days claim (2012); Mirfak; the Double Cluster (Hipparchus's 'cloudy spot'); the Perseids from Swift-Tuttle, the tears of St Lawrence; the Alpha Persei cluster; the California Nebula; Schiller's St Paul; the Chinese Tianchuan the celestial boat; the Bedouin 'bearer of the demon's head' Hamil Ra's al-Ghul"),
 "piscis_austrinus": ("Piscis Austrinus", P48, "the Southern Fish drinking the water of Aquarius, the parent of the zodiac's fishes, the fish that saved Isis or Derceto at Bambyce (Hyginus 2.41, Eratosthenes 38); Fomalhaut the fish's mouth, one of the four royal stars of Persian tradition, and its debris ring and the disputed planet Fomalhaut b (2008-2020); the 'lonely star of autumn'; Schiller's St Matthew's barrel? (verify: Schiller made it the Barrel of Meal of the widow of Zarephath); the Chinese Northern Dipper? (no); the Arabic al-Hut al-Janubi"),
 "sagitta": ("Sagitta", P48, "the arrow, the third-smallest constellation: Heracles's arrow that killed the eagle of Prometheus, or Apollo's arrow that killed the Cyclopes, buried among the Hyperboreans, or Eros's arrow (Eratosthenes 29, Hyginus 2.15); Sham; the Coathanger nearby; M71; the Babylonian arrow of the Bow star (Sirius region) as a different arrow; Schiller's Nail of the Cross; the Arabic al-Sahm"),
 "serpens": ("Serpens", P48, "the serpent held by Ophiuchus, the only constellation in two parts, Caput and Cauda, since Delporte's 1930 boundaries; the serpent of Asclepius, the healing snake at Epidaurus (Pausanias 2.27), the serpent that brought the herb of resurrection (Hyginus 2.14); Unukalhai the serpent's neck; the Eagle Nebula M16 and the Pillars of Creation in Cauda; Hoag's Object; the Babylonian serpent readings; the Bode quipu's labeling of both halves as Cauda (a slip to note); Schiller's St Benedict's serpent; the brazen serpent of Moses in Christian readings"),
 "triangulum": ("Triangulum", P48, "Deltoton, the delta of the Nile or the island of Sicily (Trinacria) placed by Zeus at Demeter's request, or the letter of Zeus's name (Eratosthenes 20, Hyginus 2.19); M33 the Triangulum Galaxy and its distance debate (Hubble 1926); Triangulum Minus, Hevelius's small triangle beside it, abolished (separate dossier); Schiller's Mitre of St Peter; the Arabic al-Muthallath; the Trinity readings"),
 "ursa_major": ("Ursa Major", P48, "Callisto the Arcadian nymph turned bear by Hera or Artemis, nearly killed by her son Arcas, set in the sky by Zeus and forbidden to bathe in Ocean by Hera's plea to Tethys (Ovid Met. 2, Fasti 2, Hyginus 2.1, Eratosthenes 1); Helice the nurse of Zeus; the Wagon of Homer, Charles's Wain, the Plough, the Big Dipper, the Drinking Gourd of the Underground Railroad; Mizar and Alcor the horse and rider and the eyesight test, Mizar the first telescopic double (Riccioli 1650) and spectroscopic double (1889); the Seven Rishis of India, the Northern Dipper of China (the emperor's chariot), the Bedouin bier and the mourning daughters; Dubhe and Merak the Pointers; the Ursa Major moving group; M81, M82, the Owl, the Pinwheel; Schiller's Peter's Boat; the Bear in Homer, Job, and the Iroquois hunt; Bode's plate; the 'Great Bear' of Blake and Tennyson"),
 "ursa_minor": ("Ursa Minor", P48, "the Little Bear: Cynosura the nurse of Zeus on Ida, or Arcas, or Phoenice (Eratosthenes 2, Hyginus 2.2); Thales's introduction of the constellation from the Phoenicians as a steering mark (Callimachus via Diogenes Laertius); Polaris the pole star since c. 500 CE and its precessional history (Thuban, Kochab), a Cepheid; Kochab and Pherkad the Guardians of the Pole; the Little Dipper; the Chinese Emperor and the Purple Enclosure; the Arabic 'the smaller bier'; Schiller's St Michael; the Bear cub in the Iroquois sky; Shakespeare's 'the guards of the ever-fixed pole'; the tail's impossible length in Aratus's critics"),
 # ---- Bayer 1603 (Keyser and de Houtman) ----
 "apus": ("Apus", BAY, "the bird of paradise, 'without feet', from the Malay trade skins sent to Europe without legs (Pigafetta 1522, Bayer's Apis Indica misprint as the bee, Kepler's correction); the southern circumpolar sky; Schiller had no southern saints for it? (verify what Schiller did with the Bayer twelve); the Chinese 'Little Wonder Bird'; the Portuguese and Dutch navigators' sky; Plancius's names"),
 "chamaeleon": ("Chamaeleon", BAY, "the chameleon, drawn by Bayer catching a fly (the future Musca) with its tongue; the Dutch voyages and the East Indies bestiary; its faint stars; the Chamaeleon dark clouds; the star-forming region; Schiller's treatment of the Bayer twelve"),
 "dorado": ("Dorado", BAY, "the dolphinfish (mahi-mahi), not the swordfish Xiphias of some atlases, chasing the flying fish Volans; the Large Magellanic Cloud within it, Magellan's and al-Sufi's 'white ox' and the Tarantula Nebula, Supernova 1987A; the south ecliptic pole; Bode's Xiphias; the dispute over the name and the fish; the Dutch voyage names"),
 "grus": ("Grus", BAY, "the crane, sacred to Hermes as the inventor of letters (Hyginus on Mercury and cranes) though the constellation is Dutch; Alnair, Gruid; carved out of Piscis Austrinus's tail; Phoenicopterus the flamingo as an alternative name (Schiller? no: in some 17th-century atlases); the Bedouin fish's tail in the same stars; the crane in Chinese sky as a different figure"),
 "hydrus": ("Hydrus", BAY, "the male water snake of the south, between the Magellanic Clouds, not the Hydra; Bayer's Hydrus; the south celestial pole's neighborhood; the confusion with Hydra in catalogues; the Dutch voyagers' sea snake"),
 "indus": ("Indus", BAY, "the Indian, an unspecified native of the East Indies or America or Madagascar holding arrows, from the Keyser-de Houtman list; the debate over whom he depicts and the colonial sky; Epsilon Indi the nearby star and its brown dwarfs; the Persian? no; Bode's plate with the arrows; the name's discomfort in modern lists"),
 "musca": ("Musca", BAY, "the fly, the only insect in the sky: Bayer's Apis the bee, later Musca Australis to distinguish it from Musca Borealis (Bode's abolished northern fly, separate dossier), Lacaille's Mouche; the chameleon's prey; the Coalsack beside it; the Dark Doodad Nebula; the Southern Cross's neighbor; the name changes through Halley, Lacaille, Bode, the IAU"),
 "pavo": ("Pavo", BAY, "the peacock: Argus Panoptes turned into a peacock by Hera, the hundred eyes in the tail (Ovid Met. 1), a late Greek gloss on a Dutch bird from the Java trade; Peacock the star named by the RAF's 1930s navigation almanac; the Peacock cluster NGC 6752; the Pavo-Indus supercluster; the south polar sky"),
 "phoenix": ("Phoenix", BAY, "the phoenix of Heliopolis, Herodotus 2.73, Ovid Met. 15, Pliny 10.2, the Physiologus, the bennu bird of Egypt, Lactantius's De ave phoenice; a Dutch constellation given the Greek bird's whole mythology after the fact; the Arabic 'the boat' and the ostrich chicks in the same stars; Ankaa; the Phoenicids; the Sculptor galaxy border; Schiller's? (the Bayer twelve in Schiller)"),
 "triangulum_australe": ("Triangulum Australe", BAY, "the southern triangle, Plancius 1589 first, Bayer 1603; Atria; the three patriarchs in Christianized southern skies; the navigators' triangle; its use as a pointer; the Dutch and Portuguese sightings before Plancius (Vespucci's 'triangle')"),
 "tucana": ("Tucana", BAY, "the toucan, from the Brazilian bird in Thevet and de Léry; Bayer's Toucan, the Small Magellanic Cloud within it and 47 Tucanae the second-greatest globular cluster (Lacaille 1751); the Dutch 'Indian magpie'; the south polar sky"),
 "volans": ("Volans", BAY, "the flying fish, Piscis Volans, chased by Dorado, from the sailors' sightings in the tropics; Bayer's plate; the shortening of the name by the IAU; the Meathook Galaxy; the Volans stream"),
 # ---- Hevelius 1690 ----
 "canes_venatici": ("Canes Venatici", HEV, "the hunting dogs Asterion and Chara held by Boötes, Hevelius's invention from stars Ptolemy left unformed, drawing on a misreading of Ptolemy's 'club' as a Greek word for dogs via Arabic (Allen's account, and Kunitzsch's correction); Cor Caroli, Charles I's or Charles II's heart named by Halley or Scarborough for the Restoration (1660s), one of the last royal star names to survive; the Whirlpool Galaxy M51 (Rosse 1845, the first spiral); M3; La Superba; the Hunting Dogs in Bode; Schiller's? (post-Schiller)"),
 "lacerta": ("Lacerta", HEV, "the lizard, Hevelius's Lacerta sive Stellio, in a starless gap between Cygnus and Andromeda; the rival names Sceptrum et Manus Iustitiae (Royer 1679, for Louis XIV) and Honores Friderici (Bode 1787, for Frederick the Great, abolished, separate dossier) laid over the same stars; BL Lacertae the blazar prototype; the 'little Cassiopeia' asterism"),
 "leo_minor": ("Leo Minor", HEV, "the little lion between Leo and Ursa Major, Hevelius 1687-90; no alpha star (Baily's omission); Praecipua; the only constellation named for another with 'minor' that is not older; Hevelius's reasons; the Bedouin 'the gazelle's leaps' in the same stars"),
 "lynx": ("Lynx", HEV, "the lynx, named by Hevelius because you needed a lynx's eyes to see it, and for Lynceus the Argonaut who could see through the earth (Apollodorus 1.9, Pindar Nem. 10); the Intergalactic Wanderer NGC 2419; the tiger in Chinese sky? no; the emptiness between Auriga and Ursa Major; Hevelius's own text on it"),
 "scutum": ("Scutum", HEV, "Scutum Sobiescianum, the shield of John III Sobieski, king of Poland, for the relief of Vienna in 1683 (Hevelius 1684 in Acta Eruditorum, 1690 atlas), the only constellation of political origin the IAU kept, shortened to Scutum; the Wild Duck cluster M11; the Scutum Star Cloud; the Great Rift; the coat of arms of the Sobieskis on the plate; UY Scuti the giant star"),
 "sextans": ("Sextans", HEV, "Sextans Uraniae, Hevelius's own sextant, burned with his observatory in the Danzig fire of 1679, placed between Leo and Hydra; the Spindle Galaxy; Cosmos Redshift 7; the Sextans dwarf; Hevelius's instruments and his refusal of telescopic sights (the Halley visit of 1679); the fire and the memorial"),
 "vulpecula": ("Vulpecula", HEV, "Vulpecula cum Ansere, the little fox with the goose, Hevelius's invention, the goose dropped by the IAU but kept in Anser the star's name; the Dumbbell Nebula M27 (Messier 1764, the first planetary nebula); the first pulsar PSR B1919+21 (Bell Burnell 1967, 'LGM-1') in it; the Coathanger asterism; Hevelius's reasoning about the fox carrying the goose to Cerberus and the Eagle"),
 # ---- Lacaille 1756 ----
 "antlia": ("Antlia", LAC, "Antlia Pneumatica, the air pump of Boyle and Papin, Lacaille's 'la Machine Pneumatique'; the Antlia Cluster; the Antlia dwarf; the emptiness of the figure; the Enlightenment sky of instruments and Lacaille's program at the Cape (1751-53, the 10,000 stars); the name's shortening"),
 "caelum": ("Caelum", LAC, "the chisel, Lacaille's 'les Burins' the engraver's burins, Caela Sculptoris; the smallest of Lacaille's figures; between Columba and Eridanus; the debate over Caelum versus Caela; the sculptor's tools with Sculptor and Pictor"),
 "carina": ("Carina", LAC, "the keel of Argo Navis, Jason's ship, cut by Lacaille into Carina, Puppis and Vela (with Pyxis as the compass), keeping Bayer's letters divided among the pieces; the Argonauts' whole myth (Apollonius, Hyginus 2.37, Eratosthenes 35: the ship built by Argus with Athena's help, the speaking beam of Dodona, the first ship), the ship in the sky shown stern-first; Canopus the pilot of Menelaus buried at the Egyptian town, the second brightest star, the Bedouin Suhayl; Eta Carinae and the Great Eruption of 1837-43 (Herschel at the Cape), the Homunculus, the Keyhole Nebula; the Diamond Cross and the False Cross; Schiller's Noah's Ark for the whole Argo; the Chinese Old Man of the South Pole (Canopus)"),
 "circinus": ("Circinus", LAC, "the drawing compasses, Lacaille's 'le Compas', beside the Southern Triangle; Circinus X-1; the Circinus galaxy; the Alpha Circini roAp star; the surveyor's set with Norma"),
 "columba": ("Columba", "introduced by Plancius on his 1592 planisphere as Columba Noachi, Noah's dove, formalized by Bayer 1603 as a subsidiary figure and by the IAU", "Noah's dove sent from the Ark (Argo beside it) with the olive branch (Genesis 8); or the dove sent by the Argonauts through the Clashing Rocks (Apollonius 2.328); Phact, Wazn; carved out of Canis Major's stars; the runaway star Mu Columbae; Schiller kept it as the Dove; the Bedouin 'the weight' (Wazn) and the ostriches"),
 "camelopardalis": ("Camelopardalis", "introduced by Plancius on his 1612-13 globe, published by Bartsch 1624, kept by the IAU", "the giraffe (camel-leopard), filling the empty space between the Bears, Cassiopeia and Auriga; Bartsch's gloss that it was the camel that carried Rebecca to Isaac (Genesis 24) and the later Christian readings; the faintness of the figure, no star above fourth magnitude; Kemble's Cascade; NGC 2403; the runaway star Alpha Camelopardalis; the Chinese Purple Enclosure officials in the same stars; Custos Messium and Tarandus once laid over its stars (separate dossiers); the confusion of 'camelopardalis' with 'camel' in atlases; the IAU's 1930 giant boundary"),
 "coma_berenices": ("Coma Berenices", "an asterism named by Conon of Samos c. 245 BCE for the hair of Berenice II of Egypt, made a constellation by Vopel (1536) and Tycho Brahe's catalogue (1602), kept by the IAU", "Berenice's Lock: the queen's hair vowed for Ptolemy III's return from the Syrian war, missing from the temple, found in the sky by Conon; Callimachus's Coma Berenices (Aetia fr. 110) and Catullus 66, its Latin translation, the lock that would rather be on her head; Ptolemy's 'nebulous mass' in Leo's tail; the Coma cluster of galaxies and Zwicky's dark matter (1933); the north galactic pole; Melotte 111; the Black Eye Galaxy; Schiller's Scourge of Christ? (verify); the Arabic 'the tuft'"),
 "crux": ("Crux", "the stars known to Ptolemy as part of Centaurus, separated as the Southern Cross by the navigators of the 1500s (Corsali 1515, Cadamosto, Vespucci), on Plancius's globe 1598 and Bayer 1603 as Crux, formalized by Royer 1679, kept by the IAU as the smallest constellation", "the Cross of the Passion in the southern sky, Dante's four stars in Purgatorio 1 (written before any European saw them, the dispute over what he knew); the Coalsack and the Jewel Box; Acrux, Mimosa, Gacrux; the pointer to the pole; the Inca Chakana and the Andean cross; the Aboriginal stingray and possum; the Maori anchor; the flags of Brazil, Australia, New Zealand, Samoa, Papua New Guinea; Schiller's? (he made the whole Centaurus Abraham); the 'crux' of Amerigo Vespucci's letters"),
 "fornax": ("Fornax", LAC, "Fornax Chemica, the chemical furnace, Lacaille's 'le Fourneau', in a bend of Eridanus; the Fornax cluster; the Fornax dwarf; the Hubble Ultra Deep Field pointed here (2003-04); Lavoisier's furnace as the model; the name shortened by the IAU"),
 "horologium": ("Horologium", LAC, "the pendulum clock, Lacaille's 'l'Horloge' for Huygens's invention; Horologium Oscillatorium; the Horologium supercluster; the faintness of the figure; the Enlightenment instruments as a set"),
 "mensa": ("Mensa", LAC, "Mons Mensae, Table Mountain at the Cape where Lacaille observed, the only constellation named for a place on earth, its 'tablecloth' cloud drawn as the Large Magellanic Cloud's edge; the faintest constellation, no star brighter than fifth magnitude; the south ecliptic pole nearby; Lacaille's Cape years"),
 "microscopium": ("Microscopium", LAC, "the microscope, Lacaille's 'le Microscope', for Hooke's and Leeuwenhoek's instrument; between Sagittarius and Piscis Austrinus; AU Microscopii and its debris disk; the emptiness of the figure; the instruments series"),
 "monoceros": ("Monoceros", "introduced by Plancius on his 1613 globe (Monoceros Unicornis), adopted by Bartsch 1624 and Hevelius, kept by the IAU", "the unicorn, from the Physiologus and the Bible's re'em, placed by Plancius in the gap between Orion's dogs; the Rosette Nebula and the Christmas Tree cluster; Plaskett's Star; Beta Monocerotis the triple (Herschel's 'most beautiful sight'); the Cone Nebula; the unicorn tapestries as the iconography; Bode's plate; the dispute over a 1564 Persian-sphere mention"),
 "norma": ("Norma", LAC, "Norma et Regula, the carpenter's square and rule, Lacaille's 'l'Équerre et la Règle'; its alpha and beta stars lost to Scorpius in the boundary changes; the Norma cluster and the Great Attractor behind it; the Norma arm of the Galaxy; the surveyor's set with Circinus"),
 "octans": ("Octans", LAC, "the octant, Hadley's 1730 instrument, Lacaille's 'l'Octans de Reflexion'; the south celestial pole within it and Sigma Octantis the faint 'Polaris Australis'; the pole's precessional path; the emptiness where every navigator looked; Lacaille's choice of Hadley over the sextant"),
 "pictor": ("Pictor", LAC, "Equuleus Pictoris, the painter's easel, Lacaille's 'le Chevalet et la Palette'; Beta Pictoris and its disk (1984), the first imaged debris disk, and its planets; Kapteyn's Star; the name shortened; the artist's tools with Sculptor and Caelum"),
 "puppis": ("Puppis", LAC, "the stern (poop deck) of Argo Navis, the largest piece of Lacaille's division of the ship; the Argonaut myth shared with Carina and Vela (assign each dossier its part: here the stern with the speaking beam of Dodona, the Argo's return, and the ship's dedication at Corinth); Naos, Zeta Puppis the hottest naked-eye star; M46, M47; the Gum Nebula; the Puppis A supernova remnant; the Vela-Puppis stream; the Bayer letters without alpha, beta, gamma"),
 "pyxis": ("Pyxis", LAC, "Pyxis Nautica, the mariner's compass, Lacaille's 'la Boussole' placed on Argo's mast, the only anachronism aboard the Argonauts' ship; Bode's Lochium Funis (the log line, abolished, separate dossier) beside it; T Pyxidis the recurrent nova; the Pyxis globular; the disputed membership in Argo"),
 "reticulum": ("Reticulum", LAC, "the reticle, Lacaille's 'le Réticule Rhomboïde', the rhombus of threads in his telescope's eyepiece; earlier Rhombus of Habrecht (1621); Zeta Reticuli and the Betty and Barney Hill star map (1961, the Fish interpretation, 1974) as the UFO legend attached to it; the Reticulum dwarf; the smallest instruments"),
 "sculptor": ("Sculptor", LAC, "Apparatus Sculptoris, the sculptor's studio, Lacaille's 'l'Atelier du Sculpteur', a bust on a block with mallet and chisel; the south galactic pole; the Sculptor Galaxy NGC 253 (Caroline Herschel 1783); the Sculptor Group; the Cartwheel Galaxy; the name shortened; the artist's set"),
 "telescopium": ("Telescopium", LAC, "the telescope, Lacaille's 'le Télescope', the aerial telescope of the Paris Observatory; shrunk by the boundary changes and by Gould, losing stars to Sagittarius, Ophiuchus and Corona Australis; Telescopium Herschelii (Bode's abolished telescope, separate dossier) as the other telescope in the sky; the Telescopium group of galaxies"),
 "vela": ("Vela", LAC, "the sails of Argo Navis; the Argonaut myth's part for the sails (the Argo under sail from Iolcus to Colchis, the voyage's stages, the return by the Danube or the Rhône); the Vela pulsar and supernova remnant (the Gum Nebula's source), the first optical pulsar? (no: the Crab) the second; Gamma Velorum Regor (the Apollo astronauts' joke names Regor, Navi, Dnoces); the False Cross; the Eight-Burst Nebula; Suhail al-Muhlif"),
 "corona_austrina": ("Corona Austrina", P48, "the southern crown, Ptolemy's Stephanos Notios, the wreath at Sagittarius's feet, the crown of Dionysus for Semele, or the wheel of Ixion, or the crown of Corona Australis as a chaplet of leaves (Hyginus 2.27); the Corona Australis molecular cloud; the Coronet cluster; Meridiana; the Bedouin 'the tortoise'; Schiller's Crown of Solomon? (verify); the 'Piscis Notius' neighbor"),
 # ---- the apocryphal nineteen ----
 "honores_friderici": ("Honores Friderici", "invented by Bode in 1787 (Friedrichs Ehre) from stars of Andromeda, Cassiopeia and Lacerta, in the Uranographia of 1801, abolished by the IAU in 1922", "a sword, pen and olive branch under a crown for Frederick the Great, who died in 1786, laid over Royer's Sceptrum et Manus Iustitiae (1679, for Louis XIV) and Hevelius's Lacerta; Bode's own text and plate; the Berlin Academy's sky; the rival royal constellations (Sceptrum Brandenburgicum, Taurus Poniatovii, Harpa Georgii, Robur Carolinum, Gladii Electorales Saxonici); its stars' fate in Andromeda and Lacerta; the sarcasm of later atlas-makers"),
 "quadrans_muralis": ("Quadrans Muralis", "invented by Lalande in 1795 for the mural quadrant of the Paris Observatory (with Lacaille), on Bode's Uranographia 1801, abolished by the IAU in 1922", "the mural quadrant that Lalande and his nephew Michel Lefrançois used to observe; the stars between Boötes, Hercules and Draco; the Quadrantid meteor shower (Quetelet 1835) which kept the dead constellation's name and its parent body 2003 EH1 and comet C/1490 Y1; the only abolished constellation with a living annual event; Lalande's Bibliographie; the pictures on Bode and Jamieson"),
 "felis": ("Felis", "invented by Lalande in 1799 (Bode's Uranographia 1801) from stars of Hydra's back and Antlia, abolished by the IAU in 1922", "the cat, Lalande's joke: 'I am very fond of cats; I will let this figure scratch on the chart' (his own words in the Bibliographie astronomique); the stars near Hydra and Antlia; its recovery in 2018 when the IAU's working group named HD 85951 'Felis'; the cat in the Egyptian sky as a different thing; Jamieson's plate of 1822 with the cat"),
 "globus_aerostaticus": ("Globus Aerostaticus", "invented by Lalande in 1798 for the Montgolfier balloon, on Bode's Uranographia 1801, abolished by the IAU in 1922", "the hot-air balloon of 1783 (the Montgolfiers, Pilâtre de Rozier, Charles's hydrogen balloon), placed south of Capricornus between Piscis Austrinus and Microscopium; Lalande's enthusiasm for aeronautics; the stars' fate in Microscopium and Piscis Austrinus; the technological sky with Machina Electrica and Officina Typographica; Bode's plate"),
 "officina_typographica": ("Officina Typographica", "invented by Bode in 1801 for the Uranographia, abolished by the IAU in 1922", "the printing office, for the 350th anniversary of Gutenberg's press (Bode dates the invention 1450), drawn with a press, type cases and a printed sheet, east of Sirius between Canis Major and Monoceros in Puppis's stars; the press in the sky as Bode's monument to his own trade (he published his atlases himself); the Mochuelo resonance (a press among the stars, for a hand-press publisher); the stars' fate; Jamieson and Burritt keeping it into the 1830s"),
 "machina_electrica": ("Machina Electrica", "invented by Bode in 1800, on the Uranographia 1801, abolished by the IAU in 1922", "the electrostatic generator (Ramsden's or van Marum's friction machine with the Leyden jar) placed south of Cetus between Fornax and Sculptor; Bode's plate; the Enlightenment's electricity (Franklin, Volta's pile of 1800 the same year); the stars' fate in Sculptor and Fornax"),
 "telescopium_herschelii": ("Telescopium Herschelii", "invented by Abbé Maximilian Hell in 1789 as two telescopes (Tubus Herschelii Major and Minor), one kept by Bode in 1801, abolished by the IAU in 1922", "William Herschel's 20-foot (or 40-foot) reflector, honoring the discovery of Uranus (1781), placed between Auriga, Lynx and Gemini where Uranus was found; Hell's two telescopes and Bode's one; Bode's own role in naming Uranus (his journey has it); Jamieson's plate; the stars in Auriga and Lynx now; the other telescope, Lacaille's Telescopium"),
 "custos_messium": ("Custos Messium", "invented by Lalande in 1775 for Charles Messier, on Bode's Uranographia 1801, abolished by the IAU in 1922", "the Harvest Keeper, a pun on Messier's name (messis, harvest), a farmer with a sickle beside Camelopardalis and Cassiopeia, near the reindeer (Tarandus) and the 'harvest' of the Great Comet of 1774; Messier's catalogue and his comet-hunting; the stars' fate in Cassiopeia, Cepheus and Camelopardalis; the French astronomers naming each other in the sky (Lalande's Felis, Messier's Custos)"),
 "sceptrum_brandenburgicum": ("Sceptrum Brandenburgicum", "invented by Gottfried Kirch in 1688 for the House of Brandenburg, on Bode's Uranographia 1801, abolished by the IAU in 1922", "the Brandenburg sceptre, Kirch's homage to the Great Elector's house, in Eridanus's bend near Lepus; Kirch and Maria Margaretha Kirch, the Berlin Academy's first astronomers; Bode's revival of it in 1782 and 1801; the stars back in Eridanus; the Prussian sky (with Honores Friderici)"),
 "lochium_funis": ("Lochium Funis", "invented by Bode in 1801 for the Uranographia, abolished by the IAU in 1922", "the log line, the knotted rope and reel for measuring a ship's speed, coiled around Pyxis on Argo's deck; the nautical instruments of the Enlightenment sky; Bode's plate; the stars' fate in Pyxis; the shortest-lived of Bode's inventions"),
 "taurus_poniatovii": ("Taurus Poniatovii", "invented by Marcin Poczobut in 1777 for King Stanisław August Poniatowski of Poland, on Bode's Uranographia 1801, abolished by the IAU in 1922", "Poniatowski's Bull, in stars between Ophiuchus, Serpens and Aquila (the V-shaped asterism like the Hyades, 66-70 Ophiuchi), created by the Vilnius astronomer for the last king of Poland, the Poniatowski arms' bull; 70 Ophiuchi the binary and the 1855 planet claim (Jacob); Barnard's Star nearby; the Polish sky with Scutum Sobiescianum; the partitions of Poland and the constellation's death"),
 "cerberus": ("Cerberus", "invented by Hevelius in 1687-90 as the three-headed dog (drawn as a three-headed snake) in Hercules's hand, on Bode's Uranographia 1801 (Cerberus et Ramus Pomifer, with the apple branch), abolished by the IAU in 1922", "the hound of Hades, Heracles's twelfth labor (Apollodorus 2.5, Hesiod Theog.), Hevelius's figure as three serpents held by Hercules; Bode's addition of the apple branch (Ramus Pomifer) of the Hesperides; the stars in Hercules now; the Cerberus of Dante and the myth's whole file; Jamieson's plate"),
 "mons_maenalus": ("Mons Maenalus", "invented by Hevelius in 1687-90 as the mountain under Boötes's feet, on Bode's Uranographia 1801, abolished by the IAU in 1922", "the Arcadian mountain of Pan, where Boötes (as Arcas) stands; Maenalus in Virgil's Eclogues and Ovid; Hevelius's landscape constellation, the only mountain in the sky besides Mensa; the stars in Boötes and Virgo now"),
 "triangulum_minus": ("Triangulum Minus", "invented by Hevelius in 1687-90 beside Triangulum, on Bode's Uranographia 1801, abolished by the IAU in 1922", "the small triangle of three faint stars (6, 10, 12 Trianguli) south of the main one; Hevelius's reasons; its stars back in Triangulum; the shortest dossier of the set, and say so"),
 "musca_borealis": ("Musca Borealis", "Plancius's Apes the bee (1612), Bartsch's Vespa, Hevelius's Musca, Bode's Musca Borealis (1801), on Aries's back, abolished by the IAU in 1922", "the northern fly on the Ram's back: Plancius's bee, the wasp, the fly, the lily (Lilium, Royer 1679 for France); the four stars 33, 35, 39 and 41 Arietis; the confusion with the southern Musca; the only insect twice in the sky; the stars back in Aries"),
 "tarandus": ("Tarandus vel Rangifer", "invented by Lemonnier in 1736 as Le Renne, the reindeer, for Maupertuis's Lapland expedition, on Bode's Uranographia 1801, abolished by the IAU in 1922", "the reindeer between Cassiopeia and Camelopardalis, for the 1736-37 expedition to Tornio that measured the arc of meridian and proved the earth flattened at the poles (Maupertuis, Clairaut, Celsius, Lemonnier); the Sami reindeer sky as the real one in the same region; Custos Messium beside it; the stars back in Cassiopeia and Camelopardalis"),
 "harpa_georgii": ("Harpa Georgii", "invented by Abbé Maximilian Hell in 1789 as Psalterium Georgianum for George III, on Bode's Uranographia 1801 as Harpa Georgii, abolished by the IAU in 1922", "George III's harp, honoring Herschel's patron, in stars between Taurus and Eridanus (10 Tauri and neighbors); Hell's Vienna observatory and his homages to Herschel and his king; the harp of David readings; the stars back in Eridanus and Taurus"),
 "turdus_solitarius": ("Turdus Solitarius", "invented by Lemonnier in 1776 as the solitary thrush (the Rodrigues solitaire, or the blue rock thrush), on Bode's Uranographia 1801, abolished by the IAU in 1922", "the bird on Hydra's tail, from Le Gentil's voyage to Rodrigues, the extinct solitaire; renamed Noctua the owl by Jamieson in 1822 and Mocking Bird by Burritt; the stars in Hydra and Libra now; the emptiness at the serpent's tail"),
 "argo_navis": ("Argo Navis", "one of Ptolemy's 48, drawn whole on Bode's Uranographia (1801), divided by Lacaille (1756) into Carina, Puppis and Vela (with Pyxis on its mast), the only Ptolemaic constellation abolished by the IAU (Delporte 1930); the 108th of the collection at Anthony's request, as the ship entire", "the ship of the Argonauts, built by Argus with Athena's help at Pagasae, with the speaking beam from the oak of Dodona, the first ship (Apollonius Argonautica, Apollodorus 1.9, Hyginus 2.37, Eratosthenes 35, Pindar Pyth. 4, Valerius Flaccus, Ovid); Jason, Medea, the Golden Fleece, the whole crew as a roster of catasterized heroes (Castor and Pollux, Heracles, Orpheus with his Lyra); the ship dedicated at Corinth or the Isthmus, the beam that killed Jason in his sleep; the ship shown stern-first in the sky, sailing backwards (Aratus 342 ff. and the ancient explanations: the Symplegades, the ship half-sunk); the Egyptian boat of Osiris and the Babylonian readings; the Bedouin Suhayl and the ship's stars in al-Sufi; Canopus the pilot of Menelaus; Bayer's plate and the single Greek-letter sequence that Lacaille's cut scattered across three constellations (why Vela and Puppis have no alpha or beta); Halley's Robur Carolinum carved from its stars (1679) and Lacaille's outrage; Lacaille's division in 1756 and the IAU's 1930 adoption of the pieces; Schiller's Noah's Ark; Dante's reading; the Argo of Catullus 64 and of Apollonius as the first ship and the loss of the golden age; Argo in the Renaissance emblem tradition (the Order of the Golden Fleece); the ship as a thing with a name, the oldest named object in the sky; where every star lives now"),
 "robur_carolinum": ("Robur Carolinum", "invented by Edmond Halley in 1679 for Charles II, the Royal Oak of Boscobel, from stars of Argo Navis, on Bode's Uranographia 1801, abolished (already by Lacaille's rejection and the IAU)", "the oak in which Charles II hid after Worcester in 1651 (the Boscobel oak), placed by Halley in his Catalogus Stellarum Australium from St Helena to please the king, at the cost of Argo's stars, which Lacaille denounced; Halley's own atlas journey (his file exists: johann bode's contemporary? no: edmond_halley is a subject, cite); the Restoration sky with Cor Caroli; the stars back in Carina and Vela; the political constellations' fate"),
}

ORDER = list(SIGNS.keys())

if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    for slug, (name, status, pointers) in SIGNS.items():
        text = f"""# {name}: research brief

Bode collection research, Anthony 2026-09-12, separate from the atlas. Appended to
PROMPT_TEMPLATE_CONSTELLATION.md by atlas_tools/codex_dossier_bode.py.

---

FIGURE. {name}: {status}. On Johann Elert Bode's Uranographia (1801) and in the Bode collection
on chain (830 stars in 109 groups). Give its status plainly at the top: kept by the IAU with its
1930 boundaries, or abolished, and where its stars went.

THREADS TO PULL, each to be verified against the sources and dated: {pointers}.

STANCE. Myth as fully as fact. Every claim labeled: documented fact, scholarly reconstruction,
tradition, disputed, legend, modern invention; the first appearance of each story, who spread it,
and what evidence exists. Where a thread above is marked '(verify)' or '(no: ...)', treat it as a
lead to check, not a fact, and report what you found. Absence of evidence is a finding: say what
could not be traced. For an abolished figure, everything that survives about it, however little.
"""
        open(os.path.join(OUT, f"{slug}.brief.md"), "w").write(text)
    print("wrote", len(SIGNS), "briefs")
