#!/usr/bin/env python3
"""Write one brief per text encoding into encodings/briefs/, in order of first appearance."""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "briefs")

CODES = [
 ("morse_and_telegraph_codes", "Morse code and the telegraph codes", "Morse and Vail's code of 1844 (the American Morse) and the International Morse of 1851 (Gerke, the 1865 ITU adoption), the letter frequencies from the printer's type case, the variable-length design as the first compression, the Cooke-Wheatstone needle codes, the prosigns and SOS (1906, Berlin), the Morse in radio and the 1999 end of the maritime watch, the 2004 @ addition; Morse as the ancestor of every encoding here"),
 ("baudot_murray_and_ita2", "Baudot, Murray and the five-bit teleprinter codes (ITA2)", "Émile Baudot's five-unit code of 1874 and his printing telegraph, the piano-key keyboard, Donald Murray's rearrangement of 1901 for the typewriter keyboard with the figures/letters shifts, the Western Union and Teletype adoption, the CCITT International Telegraph Alphabet No. 2 of 1932, the baud named for Baudot, the teleprinter networks (Telex) and the code's survival in radioteletype (RTTY) and in amateur radio to this day, the 1963 replacement by ASCII, the punched paper tape and its holes"),
 ("hollerith_and_punched_card_codes", "Hollerith and the punched-card codes", "Herman Hollerith's cards for the 1890 US census (the Jacquard and the railway ticket as models), the 80-column IBM card of 1928 with its zone and digit rows, the Hollerith code's letters (a zone punch plus a digit punch), the card as the data medium of the twentieth century, the BCDIC six-bit codes of the 1950s (IBM 704, 1401) that grew from it, the card's constraints that shaped EBCDIC, the 'do not fold, spindle or mutilate' culture, the end of the card in the 1980s"),
 ("fieldata_and_the_military_and_vendor_codes", "Fieldata and the early computer codes (the 1950s vendor and military codes)", "the US Army's Fieldata code (1956-59) as the first attempt at a common military character set and its influence on ASCII's layout, the vendor six-bit codes (IBM's BCD variants, UNIVAC's, the CDC display code, the DEC SIXBIT), the ARPANET's need for a common code, Bemer's survey of the sixty-odd codes in use at IBM alone (his 1960 memo), the state of babel that ASCII was meant to end"),
 ("ascii", "ASCII", "the American Standard Code for Information Interchange: the ASA X3.4 of 1963 (the first edition without lowercase), the 1965/1967 revisions that added the lowercase letters and settled the control characters, Bob Bemer's role (the escape character, the backslash, the committee work, his own account on bobbemer.com) and Hugh McGregor Ross, the seven-bit design and the parity bit, the control characters' names and their origins (BEL, DEL as all-ones, the tape-punch logic), the 1968 Johnson memorandum making ASCII the federal standard, RFC 20 (1969, Vint Cerf) making it the ARPANET's, the ISO 646 international version and its national variants (the Danish, German, Swedish letters in the # $ @ [ \\ ] positions, the curly-brace problem), the 1986 revision, ASCII art, the persistence of every ASCII decision in Unicode's first 128"),
 ("ebcdic", "EBCDIC", "IBM's Extended Binary Coded Decimal Interchange Code of 1963-64 for System/360, grown from the punched-card BCDIC (the letters in non-contiguous blocks because of the card's zone punches), the eight-bit design, the IBM decision to ship EBCDIC rather than ASCII (the 360's ASCII bit that was never used, Bob Bemer's fury, the 1964 story), the code page variants (037, 500, 1047 and the dozens of national pages), EBCDIC vs ASCII conversion as a lifelong industry, the survival in mainframes, banks and airlines to this day, the 'EBCDIC is dead' jokes and the reality"),
 ("iso_646_and_the_seven_bit_national_variants", "ISO 646 and the seven-bit national variants (the # $ @ [ \\ ] wars)", "the 1967-73 ISO 646 standard as the international ASCII, the ten or twelve code positions left to national choice, the national versions (the German DIN 66003 with Ä Ö Ü in the bracket positions, the Swedish, Danish-Norwegian, French, Italian, Spanish, Japanese JIS X 0201 with the yen sign for the backslash, the Chinese), the programmers' misery (C code in Scandinavian ISO 646 and the trigraphs), the international reference version and the currency sign ¤ in place of $, the transition to eight-bit codes in the 1980s and the ghosts left in email and Usenet"),
 ("iso_2022_and_the_shift_sequences", "ISO 2022 and the escape-sequence encodings", "the ISO/IEC 2022 framework of 1973 (ECMA-35): the G0-G3 sets, the escape sequences that switch character sets, the 94- and 96-character sets, the C0 and C1 controls; its use for the East Asian encodings (ISO-2022-JP in Japanese email, ISO-2022-KR, ISO-2022-CN), the terminal escape sequences (VT100, ANSI X3.64) that descend from it, the elegance and the fragility of stateful encodings, the reason UTF-8 won"),
 ("iso_8859_and_latin_1", "ISO 8859 and the Latin-1 family", "the ISO/IEC 8859 series (1987 on): 8859-1 Latin-1 for Western Europe (the ECMA-94 origin, the DEC Multinational Character Set as ancestor), the parts for Central European, South European, North European, Cyrillic, Arabic, Greek, Hebrew, Turkish, Nordic, Thai, Baltic, Celtic, Latin-9 with the euro (1998); the first 256 code points of Unicode taken from Latin-1; the web's early default; the Windows-1252 superset and the smart-quote mojibake; the withdrawal of the parts in the 2000s"),
 ("code_pages_437_1252_and_the_vendor_eight_bit_sets", "Code pages: 437, 850, 1252 and the vendor eight-bit sets (IBM, Microsoft, Apple, DEC)", "the IBM PC's code page 437 of 1981 with its box-drawing characters and its Greek and math signs, 850 for Western Europe, the OEM vs ANSI split in Windows, Windows-1252 and the 0x80-0x9F smart quotes and euro, the Mac OS Roman set with its Apple logo, the Atari and Commodore PETSCII sets, the DEC MCS, the Amstrad, the code page numbering and IBM's registry, the DOS-era text art (the ANSI art scene, the BBS, the demoscene's use of 437), the mojibake of 1252 read as Latin-1 and vice versa, the code pages' persistence in ZIP filenames and databases"),
 ("koi8_and_the_cyrillic_encodings", "KOI8 and the Cyrillic encodings", "KOI-7 and KOI8 (1974, GOST 19768-74), the KOI8-R design by Andrey Chernov (1993, RFC 1489) in which stripping the eighth bit yields a readable Latin transliteration (so that a Russian text survives a seven-bit path as a rough Latin one), KOI8-U for Ukrainian, the rival Cyrillic encodings (CP866 in DOS, Windows-1251, ISO 8859-5, the Mac Cyrillic) and the four-way mojibake of the Russian internet of the 1990s (the 'krakozyabry'), the Unicode resolution, the Bulgarian and Serbian variants"),
 ("east_asian_double_byte_encodings", "The East Asian double-byte encodings: Shift-JIS, EUC, GB 2312, GBK, Big5", "the problem of thousands of characters in a byte world: JIS X 0208 (1978) and the Shift-JIS encoding of Microsoft and ASCII Corporation (1982), EUC-JP, EUC-KR and KS X 1001, GB 2312 (1980) and the simplified-character world, GBK and GB 18030 (the mandatory Chinese standard that encodes all of Unicode), Big5 (1984) for Taiwan and Hong Kong with its HKSCS supplement, the half-width katakana, the byte-value collisions with ASCII's backslash and the '5c' problem, the mojibake (文字化け) as a Japanese word and experience, the vendor extensions, the long coexistence with Unicode in Japan and the resistance to it"),
 ("unicode", "Unicode and ISO 10646", "the 1988 Joe Becker proposal ('Unicode 88'), the Xerox and Apple origins (Becker, Lee Collins, Mark Davis), the 16-bit 'sixteen bits are enough' assumption and the 1996 surrogate expansion to 21 bits, the merger with ISO 10646's Universal Character Set (the 1991-93 negotiations, the failed DIS 10646 of 1990), Unicode 1.0 (1991), the Consortium's structure and membership (the companies, the national bodies), the design principles (characters not glyphs, the stability policy, normalization forms, the bidi algorithm), the Han unification (the Ideographic Rapporteur Group, the Japanese objections, the source-separation rule), the encoding of scripts over time (which scripts got in when, the Klingon rejection, the emoji, the Tengwar and Shavian in the SMP), the current size (the versions and their character counts), Unicode as a political institution; Davis's and Whistler's accounts, the Consortium's history page"),
 ("utf_16_and_ucs_2", "UTF-16 and UCS-2", "the original 16-bit Unicode (UCS-2) in Windows NT (1993), Java (1995) and JavaScript, the surrogate pairs of Unicode 2.0 (1996) that made it UTF-16, the byte-order mark (U+FEFF) and the endianness problem (UTF-16LE and BE), the legacy of the 16-bit assumption in every API that counts 'characters' as code units (the emoji that break string lengths), the 'UTF-16 considered harmful' arguments and the utf8everywhere manifesto, the platforms that remain UTF-16 inside (Windows, Java, .NET, JavaScript, Qt)"),
 ("utf_8", "UTF-8", "the origin: Ken Thompson and Rob Pike, the New Jersey diner placemat, September 1992, in response to the X/Open FSS-UTF proposal (Pike's own account, quoted in full), the Plan 9 implementation within days, the design (ASCII-compatible, self-synchronizing lead bytes and continuation bytes, the 1-4 byte lengths, the sorting order preserved), the 1993 USENIX paper 'Hello World or Καλημέρα κόσμε or こんにちは 世界', RFC 2044 (1996), RFC 2279, RFC 3629 (2003) restricting it to four bytes, the overlong-sequence security flaw and the 'Modified UTF-8' of Java, the IETF's 1998 policy (RFC 2277) making it the default, the web's adoption curve (Google's 2008 figures, the W3C's 98 percent), the BOM debate, UTF-8 as the encoding of this repo's quipus and of the Dogecoin OP_RETURN inscriptions (a line, not a section)"),
 ("emoji_and_the_encoding_of_pictures", "Emoji and the encoding of pictures", "the Japanese carrier emoji of 1999 (Shigetaka Kurita's 176 for NTT DoCoMo, the SoftBank and au sets and their incompatibility), the Google and Apple proposal to Unicode (2007-2010) and Unicode 6.0's 722 emoji (2010), the Consortium's emoji subcommittee and the proposal process (the criteria, the rejections), the skin-tone modifiers (2015), the ZWJ sequences for families and professions, the flag sequences from regional indicators, the vendor design differences (the gun that became a water pistol, the Google blob to the Apple style), the Oxford word of the year 2015, the emoji as the first new script adopted worldwide, the critiques (the Consortium as a private club, the cultural politics of which food and which flag), Kurita's set in MoMA (2016)"),
 ("bidi_shaping_and_the_complex_scripts", "Bidirectional text and complex-script shaping: Hebrew, Arabic, the Indic scripts and the encoding of writing that is not left-to-right Latin", "the Unicode bidirectional algorithm (UAX 9) and the problems of mixed Hebrew/Arabic and Latin (the mirrored brackets, the numbers, the explicit controls and the isolates), the Arabic presentation forms vs the shaping engines (contextual forms, ligatures, the lam-alef, the Arabic in early code pages), the Indic scripts' abugida encoding (the virama model, the reordering of vowel signs, the OpenType shaping in Uniscribe, HarfBuzz and CoreText), the Thai and Khmer without spaces, the Mongolian vertical text, the Tibetan stacks and the 1990s ISO fight over Tibetan, the CJK vertical text, the fonts and the rendering stack as the other half of an encoding, the 'Unicode encodes characters, not glyphs' principle tested; the Hebrew and Arabic alphabets in this repo's alphabets set as the ancient half of the same story"),
]

SIGNS = {}
for i, (slug, name, pointers) in enumerate(CODES, start=1):
    SIGNS[f"{i:02d}_{slug}"] = (name, f"encoding {i} of {len(CODES)} in this set", pointers)

ORDER = list(SIGNS.keys())

if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    for slug, (name, status, pointers) in SIGNS.items():
        text = f"""# {name}: research brief

Text-encodings research, Anthony 2026-09-15, separate from the atlas. Appended to
PROMPT_TEMPLATE_ENCODINGS.md by tools/codex_dossier_set.py.

---

ENCODING. {name}: {status}. Give at the top the standard number, the year, the bit width, the
repertoire and the current status.

THREADS TO PULL, each to be verified against the sources and dated: {pointers}.

STANCE. Folklore as fully as fact, labeled. Every claim labeled: documented standard or text,
participant recollection, scholarly reconstruction, disputed, folklore, modern invention. Give
the worked examples byte by byte. Where a story has one witness (the placemat, the 360's unused
ASCII bit), say so. Absence of evidence is a finding.
"""
        open(os.path.join(OUT, f"{slug}.brief.md"), "w").write(text)
    print("wrote", len(SIGNS), "briefs")
