#!/usr/bin/env python3
"""Write one brief per writing system into alphabets/briefs/, roughly in order of first attestation."""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "briefs")

SCRIPTS = [
 ("egyptian_hieroglyphs", "Egyptian hieroglyphs (and hieratic and demotic)", "logographic-consonantal, c. 3200 BCE to 394 CE (the Philae graffito); the uniliteral signs as the seed of the alphabet; the Narmer palette, the Rosetta Stone and Champollion (1822, the Lettre à M. Dacier), Young; hieratic and demotic; the direction facing the animals; the cartouche; the Book of the Dead; the sign lists (Gardiner); the Coptic afterlife; the hieroglyphs in the Renaissance (Horapollo, Kircher's Oedipus Aegyptiacus and his fantasies)"),
 ("cuneiform", "Cuneiform (Sumerian, Akkadian and the Ugaritic alphabet)", "the wedge script from Uruk c. 3300 BCE, logo-syllabic; Sumerian, Akkadian, Hittite, Elamite, Old Persian; the Ugaritic cuneiform alphabet of 30 signs (c. 1400 BCE) and its abecedaries as the first attested alphabetical order; the Behistun inscription and Rawlinson, Grotefend, Hincks, the 1857 test; the libraries of Ashurbanipal and Ebla; the last dated tablet (75 CE)"),
 ("proto_sinaitic_and_proto_canaanite", "Proto-Sinaitic and Proto-Canaanite: the first alphabet", "the Serabit el-Khadim inscriptions (Petrie 1905, Gardiner's reading of b'lt 1916), Wadi el-Hol (c. 1900-1800 BCE, Darnell), the acrophonic derivation from hieroglyphs, the Lachish dagger, the Izbet Sartah ostracon abecedary (c. 1100 BCE), Sass's and Rollston's datings, the semitic miners hypothesis, Goldwasser; the 22-letter Canaanite inventory settling by c. 1050 BCE"),
 ("phoenician", "The Phoenician alphabet", "the 22 consonants, right to left, the Ahiram sarcophagus (c. 1000 BCE), the Byblos inscriptions, the Mesha stele, the Kilamuwa stele, the Carthaginian Punic and Neo-Punic; the mother of Greek, Aramaic, Hebrew, Arabic and, by descent, of Latin and Cyrillic; Herodotus on Cadmus and the phoinikeia grammata (5.58); the Ugaritic and Proto-Canaanite order; the letter names and their meanings; Naveh's early history"),
 ("aramaic", "The Aramaic alphabet and its daughters", "from Phoenician c. 900 BCE, the imperial script of Assyria, Babylon and Persia, the Elephantine papyri, the square script that became Hebrew, the Nabataean script that became Arabic, Syriac (Estrangela, Serto, Madnhaya), Palmyrene, Mandaic, the Brahmi question (Aramaic as its possible model), Kharosthi, Sogdian and the scripts of the Silk Road down to Uyghur, Mongolian and Manchu"),
 ("hebrew_alphabet", "The Hebrew alphabet (Paleo-Hebrew and the square script)", "the Paleo-Hebrew script (the Gezer calendar c. 925 BCE, the Siloam inscription, the Lachish letters) and the Samaritan script that continues it; the square Aramaic script adopted after the exile, the Dead Sea Scrolls, the Masoretic vowel points (Tiberian, c. 800), the final letters, the sofer's rules for the Torah scroll, Rashi script, the letters as numbers, gematria, the Sefer Yetzirah's 22 letters as three mothers, seven doubles and twelve simples, the Otiyot de-Rabbi Akiva, the letters in the Zohar, Hebrew typography from Soncino to Frank-Ruehl, Ben-Yehuda and the revival"),
 ("greek_alphabet", "The Greek alphabet", "the adaptation from Phoenician with the vowel innovation (aleph to alpha, he to epsilon, yod to iota, ayin to omicron, waw to upsilon), the date debate (eighth century BCE consensus, Naveh's eleventh, the Dipylon oinochoe and Nestor's cup c. 740-730), the local scripts (Jeffery's LSAG), the Ionic standardization at Athens in 403 BCE (Euclid's archonship), the archaic letters digamma, koppa, san, sampi, boustrophedon, the letter names, the numerals and isopsephy, the uncial, the minuscule of the ninth century, the accents and breathings (Aristophanes of Byzantium), the Greek magical papyri and the seven vowels, Coptic and Gothic and Cyrillic as daughters, the modern monotonic reform of 1982"),
 ("etruscan_and_old_italic", "The Etruscan and Old Italic alphabets", "from the Euboean Greek of Cumae and Pithekoussai, the Marsiliana d'Albegna abecedarium (c. 700 BCE), right to left, the missing voiced stops, the Etruscan numerals, the Old Italic scripts (Oscan, Umbrian, Venetic, Lepontic, Raetic, Camunic) and the runic-origin theory that points at them, the Etruscan language still only partly understood, the Liber Linteus of Zagreb, the Pyrgi tablets"),
 ("latin_alphabet", "The Latin alphabet", "from Etruscan via Cumaean Greek, the Praeneste fibula (and its authenticity dispute), the Lapis Niger, the Duenos inscription; the 21 letters of the Republic, G invented by Spurius Carvilius Ruga (c. 230 BCE), Y and Z borrowed for Greek words, Claudius's three failed letters, J U W as medieval and early-modern splits; the scripts: capitalis, rustic, uncial, half-uncial, the national hands, Carolingian minuscule (Alcuin, Corbie), Gothic textura, humanist minuscule and italic (Poggio, Niccoli, Aldus), the roman type of Jenson and Griffo; the alphabet's spread with Rome, the Church and the empires; the Latin alphabet in Turkish (1928), Vietnamese, Swahili, the pinyin; ligatures, the ampersand, the long s, the thorn's death"),
 ("arabic_alphabet", "The Arabic alphabet", "from Nabataean Aramaic (the Namara inscription 328, the Zabad inscription 512), the 28 letters, the abjad order and the numerical values, the modern hijai order, the dots (i'jam) and the vowel marks (tashkil) and their introduction under Abu al-Aswad and al-Hajjaj, the Quranic manuscripts (Sanaa, Birmingham), Kufic, naskh, thuluth, nastaliq, Ibn Muqla's proportioned script, Ibn al-Bawwab, calligraphy as the sacred art, the letters in Sufism and ilm al-huruf (Ibn Arabi, al-Buni, the Hurufis), the Arabic script for Persian, Urdu, Ottoman Turkish, Malay, Swahili, the Turkish abandonment of 1928, Arabic typography and the digital challenge"),
 ("brahmi_and_indic_scripts", "Brahmi and the Indic scripts (Devanagari and its sisters)", "Brahmi in the Ashokan edicts (c. 250 BCE), the abugida principle (inherent vowel, matras), the Aramaic-derivation vs indigenous-origin debate, Kharosthi in the northwest, the Gupta script, the Siddham of the Buddhist East, Nagari and Devanagari (the Sanskrit tradition, the Hindi standard), Bengali, Gurmukhi, Gujarati, Tamil, Telugu, Kannada, Malayalam, Sinhala, Tibetan, Burmese, Thai, Khmer, Javanese and Balinese as the Southeast Asian daughters; the varnamala order as a phonetic science (Panini), the Om, the letters in tantra (the matrika, bija mantras), Salomon's Indian Epigraphy"),
 ("runes", "The runes (Elder Futhark, Younger Futhark, Anglo-Saxon futhorc)", "the 24 runes of the Elder Futhark in three aettir, the Kylver stone (c. 400) and the Vimose comb, the origin debate (Old Italic/Raetic, Latin, Greek; the Marcomanni; Odin's self-hanging in Hávamál 138-141 as the myth), the rune names and the three rune poems (Anglo-Saxon, Norwegian, Icelandic, quoted), the Younger Futhark of 16, the futhorc of 29-33, the medieval runes and the Dalecarlian survival to the 1900s, the Kensington stone forgery, the Nazi appropriation (Guido von List's Armanen runes) and the postwar rune magic revival, the Bluetooth logo, Tolkien's Cirth"),
 ("ogham", "Ogham", "the 20 letters in four aicmí plus the forfeda, notches on the edge of standing stones, c. 400-600 CE in Ireland, Wales, Scotland, Man, the Book of Ballymote's Auraicept na nÉces and In Lebor Ogaim (the tree names and the many other oghams), the origin theories (Latin grammarians' alphabet, a cipher, a tally), Ogma as the mythical inventor, the CIIC corpus (Macalister), McManus's Guide to Ogham (1991), Graves's The White Goddess tree calendar and the scholarly rejection of it, the modern neo-pagan ogham"),
 ("armenian_and_georgian", "The Armenian and Georgian alphabets", "Mesrop Mashtots and the Armenian alphabet of 405 (Koriun's Life), the 36 letters and their numerical values, the erkatagir, bolorgir and notrgir scripts, the Matenadaran; the Georgian scripts (Asomtavruli, Nuskhuri, Mkhedruli), the Bir el Qutt inscriptions of 430, the Pharnavaz legend, the Mashtots question, the three-script tradition and the 2016 UNESCO listing"),
 ("glagolitic_and_cyrillic", "Glagolitic and Cyrillic", "Cyril and Methodius, the Moravian mission of 863, Glagolitic as Cyril's invention (its models: Greek minuscule, Hebrew, Samaritan, Coptic; the Christian cross-triangle-circle theory), the Cyrillic alphabet made at Preslav under Simeon (c. 893) by Clement of Ohrid's circle, the Old Church Slavonic corpus, the letter-numerals with the titlo, Peter the Great's civil script of 1708, the Bolshevik reform of 1918, the Cyrillic alphabets of the Soviet nationalities and their post-1991 latinizations (Azerbaijan, Uzbekistan, Kazakhstan 2025), the Croatian Glagolitic survival to the twentieth century, Cyrillic typography"),
 ("hangul", "Hangul", "King Sejong's Hunminjeongeum of 1443/1446 (the promulgation text, the Haerye explanation, quoted), the featural design: the consonant shapes drawn from the articulators, the vowels from heaven, earth and man, the syllable blocks, the 28 original letters and the 24 of today, the Phagspa question (Ledyard), the yangban resistance and the 'women's script', the 1894 official status, the Japanese suppression, the North-South orthographic split, Hangul Day, the Cia-Cia adoption in Indonesia (2009), Hangul on the keyboard"),
 ("invented_alphabets", "Invented and reformed alphabets: Enochian, Cherokee, Shavian and the shorthand scripts", "Enochian: Dee and Kelley's 21 letters received in 1583 (the Liber Loagaeth, the 48 Calls, Laycock's Complete Enochian Dictionary), the Golden Dawn and Crowley's use; Sequoyah's Cherokee syllabary (1821) and its 86 signs, the fastest literacy adoption on record; the Vai and other West African invented scripts; Shaw's alphabet (the 1962 Androcles and the Lion) and Quikscript; Tironian notes, Pitman and Gregg shorthand; Deseret; the Unifon and Initial Teaching Alphabet; Tengwar; the Voynich script as the undeciphered case; Bliss symbols and Blissymbolics; the pattern in invented alphabets and why almost all fail"),
]

SIGNS = {}
for i, (slug, name, pointers) in enumerate(SCRIPTS, start=1):
    SIGNS[f"{i:02d}_{slug}"] = (name, f"writing system {i} of {len(SCRIPTS)} in this set", pointers)

ORDER = list(SIGNS.keys())

if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    for slug, (name, status, pointers) in SIGNS.items():
        text = f"""# {name}: research brief

Alphabets research, Anthony 2026-09-15, separate from the atlas. Appended to
PROMPT_TEMPLATE_ALPHABETS.md by tools/codex_dossier_set.py.

---

SCRIPT. {name}: {status}. Give at the top the type, the inventory, the direction, the period,
the region, the parent script and the daughters.

THREADS TO PULL, each to be verified against the sources and dated: {pointers}.

STANCE. Legend as fully as fact. Every claim labeled: documented artefact or text, scholarly
reconstruction, tradition, disputed, legend, modern invention. Where a thread above names a
dispute, present both sides with their evidence. Give the sign table in Unicode where the
script is encoded. Absence of evidence is a finding.
"""
        open(os.path.join(OUT, f"{slug}.brief.md"), "w").write(text)
    print("wrote", len(SIGNS), "briefs")
